"""API security hypothesis schema (Stage R49.3).

An :class:`APISecurityHypothesisPlan` is a deterministic research
hypothesis about possible API-level security-control behavior. It answers
the research question:

    "Which API security review hypothesis follows from the supplied
     context?"

Hard boundaries encoded here:

- Research hypothesis only: no exploit claim, no vulnerability
  confirmation, no API attack instructions, no fuzzing, no payload, no
  authentication/authorization bypass, no IDOR/BOLA/SQLi/XSS/SSRF
  exploitation, no token manipulation, no credential testing, no attack
  sequence, no execution.
- Technology presence is never a hypothesis of weakness by itself.
- Boundary with R46/R47/R48: object-level authorization hypotheses remain
  R46, JWT/claim validation remains R47 and OAuth protocol flow remains
  R48; R49 hypotheses are API-level postures only.
- Closed vocabularies: hypothesis type, hypothesis state, supporting
  signals, confidence, priority, rationale and limitations are
  closed/bounded.
- Confidence and priority reuse the shared evidence-confidence
  vocabulary. Priority means "how useful is further research of this API
  hypothesis?"; it is NOT severity, exploitability, CVSS or vulnerability
  probability.
- Bounded, privacy-safe, JSON serializable.

No I/O, no network, no LLM, no Mongo, no execution of any kind is
represented here.
"""

from __future__ import annotations

import re

from pydantic import BaseModel, ConfigDict, Field, field_validator

from ai.schemas.evidence_confidence import CONFIDENCE_LEVELS

API_SECURITY_HYPOTHESIS_RULE_VERSION = "r49-3"
RULE_VERSION = API_SECURITY_HYPOTHESIS_RULE_VERSION

# ---------------------------------------------------------------------------
# Closed hypothesis vocabulary
# ---------------------------------------------------------------------------

TYPE_API_AUTHENTICATION_GAP = "API_AUTHENTICATION_GAP"
TYPE_API_AUTHORIZATION_GAP = "API_AUTHORIZATION_GAP"
TYPE_FUNCTION_LEVEL_AUTHORIZATION_GAP = "FUNCTION_LEVEL_AUTHORIZATION_GAP"
TYPE_TENANT_ISOLATION_GAP = "TENANT_ISOLATION_GAP"
TYPE_INPUT_VALIDATION_GAP = "INPUT_VALIDATION_GAP"
TYPE_SCHEMA_VALIDATION_GAP = "SCHEMA_VALIDATION_GAP"
TYPE_MASS_ASSIGNMENT_RISK = "MASS_ASSIGNMENT_RISK"
TYPE_HTTP_METHOD_CONTROL_GAP = "HTTP_METHOD_CONTROL_GAP"
TYPE_METHOD_OVERRIDE_RISK = "METHOD_OVERRIDE_RISK"
TYPE_API_VERSIONING_RISK = "API_VERSIONING_RISK"
TYPE_RESOURCE_EXPOSURE_RISK = "RESOURCE_EXPOSURE_RISK"
TYPE_SENSITIVE_FIELD_EXPOSURE_RISK = "SENSITIVE_FIELD_EXPOSURE_RISK"
TYPE_ERROR_INFORMATION_DISCLOSURE = "ERROR_INFORMATION_DISCLOSURE"
TYPE_DEBUG_INFORMATION_EXPOSURE = "DEBUG_INFORMATION_EXPOSURE"
TYPE_RATE_LIMIT_CONTROL_GAP = "RATE_LIMIT_CONTROL_GAP"
TYPE_RESOURCE_LIMIT_CONTROL_GAP = "RESOURCE_LIMIT_CONTROL_GAP"
TYPE_PAGINATION_CONTROL_GAP = "PAGINATION_CONTROL_GAP"
TYPE_QUERY_COMPLEXITY_CONTROL_GAP = "QUERY_COMPLEXITY_CONTROL_GAP"
TYPE_BATCH_OPERATION_CONTROL_GAP = "BATCH_OPERATION_CONTROL_GAP"
TYPE_FILE_UPLOAD_CONTROL_GAP = "FILE_UPLOAD_CONTROL_GAP"
TYPE_FILE_DOWNLOAD_CONTROL_GAP = "FILE_DOWNLOAD_CONTROL_GAP"
TYPE_CORS_CONTROL_GAP = "CORS_CONTROL_GAP"
TYPE_GRAPHQL_INTROSPECTION_RISK = "GRAPHQL_INTROSPECTION_RISK"
TYPE_GRAPHQL_AUTHORIZATION_GAP = "GRAPHQL_AUTHORIZATION_GAP"
TYPE_GRAPHQL_QUERY_COMPLEXITY_GAP = "GRAPHQL_QUERY_COMPLEXITY_GAP"
TYPE_API_KEY_CONTROL_GAP = "API_KEY_CONTROL_GAP"
TYPE_WEBHOOK_SIGNATURE_CONTROL_GAP = "WEBHOOK_SIGNATURE_CONTROL_GAP"
TYPE_WEBHOOK_REPLAY_CONTROL_GAP = "WEBHOOK_REPLAY_CONTROL_GAP"
TYPE_CONTENT_TYPE_CONTROL_GAP = "CONTENT_TYPE_CONTROL_GAP"
TYPE_API_SECURITY_CONTROL_PRESENT = "API_SECURITY_CONTROL_PRESENT"
TYPE_MISSING_API_CONTEXT = "MISSING_API_CONTEXT"
TYPE_UNKNOWN = "UNKNOWN"

HYPOTHESIS_TYPES: tuple[str, ...] = (
    TYPE_API_AUTHENTICATION_GAP,
    TYPE_API_AUTHORIZATION_GAP,
    TYPE_FUNCTION_LEVEL_AUTHORIZATION_GAP,
    TYPE_TENANT_ISOLATION_GAP,
    TYPE_INPUT_VALIDATION_GAP,
    TYPE_SCHEMA_VALIDATION_GAP,
    TYPE_MASS_ASSIGNMENT_RISK,
    TYPE_HTTP_METHOD_CONTROL_GAP,
    TYPE_METHOD_OVERRIDE_RISK,
    TYPE_API_VERSIONING_RISK,
    TYPE_RESOURCE_EXPOSURE_RISK,
    TYPE_SENSITIVE_FIELD_EXPOSURE_RISK,
    TYPE_ERROR_INFORMATION_DISCLOSURE,
    TYPE_DEBUG_INFORMATION_EXPOSURE,
    TYPE_RATE_LIMIT_CONTROL_GAP,
    TYPE_RESOURCE_LIMIT_CONTROL_GAP,
    TYPE_PAGINATION_CONTROL_GAP,
    TYPE_QUERY_COMPLEXITY_CONTROL_GAP,
    TYPE_BATCH_OPERATION_CONTROL_GAP,
    TYPE_FILE_UPLOAD_CONTROL_GAP,
    TYPE_FILE_DOWNLOAD_CONTROL_GAP,
    TYPE_CORS_CONTROL_GAP,
    TYPE_GRAPHQL_INTROSPECTION_RISK,
    TYPE_GRAPHQL_AUTHORIZATION_GAP,
    TYPE_GRAPHQL_QUERY_COMPLEXITY_GAP,
    TYPE_API_KEY_CONTROL_GAP,
    TYPE_WEBHOOK_SIGNATURE_CONTROL_GAP,
    TYPE_WEBHOOK_REPLAY_CONTROL_GAP,
    TYPE_CONTENT_TYPE_CONTROL_GAP,
    TYPE_API_SECURITY_CONTROL_PRESENT,
    TYPE_MISSING_API_CONTEXT,
    TYPE_UNKNOWN,
)

VALIDATION_GAP_HYPOTHESIS_TYPES: tuple[str, ...] = (
    TYPE_API_AUTHENTICATION_GAP,
    TYPE_API_AUTHORIZATION_GAP,
    TYPE_FUNCTION_LEVEL_AUTHORIZATION_GAP,
    TYPE_TENANT_ISOLATION_GAP,
    TYPE_INPUT_VALIDATION_GAP,
    TYPE_SCHEMA_VALIDATION_GAP,
    TYPE_HTTP_METHOD_CONTROL_GAP,
    TYPE_RATE_LIMIT_CONTROL_GAP,
    TYPE_RESOURCE_LIMIT_CONTROL_GAP,
    TYPE_PAGINATION_CONTROL_GAP,
    TYPE_QUERY_COMPLEXITY_CONTROL_GAP,
    TYPE_BATCH_OPERATION_CONTROL_GAP,
    TYPE_FILE_UPLOAD_CONTROL_GAP,
    TYPE_FILE_DOWNLOAD_CONTROL_GAP,
    TYPE_CORS_CONTROL_GAP,
    TYPE_GRAPHQL_AUTHORIZATION_GAP,
    TYPE_GRAPHQL_QUERY_COMPLEXITY_GAP,
    TYPE_API_KEY_CONTROL_GAP,
    TYPE_WEBHOOK_SIGNATURE_CONTROL_GAP,
    TYPE_WEBHOOK_REPLAY_CONTROL_GAP,
    TYPE_CONTENT_TYPE_CONTROL_GAP,
)

RISK_HYPOTHESIS_TYPES: tuple[str, ...] = (
    TYPE_MASS_ASSIGNMENT_RISK,
    TYPE_METHOD_OVERRIDE_RISK,
    TYPE_API_VERSIONING_RISK,
    TYPE_RESOURCE_EXPOSURE_RISK,
    TYPE_SENSITIVE_FIELD_EXPOSURE_RISK,
    TYPE_ERROR_INFORMATION_DISCLOSURE,
    TYPE_DEBUG_INFORMATION_EXPOSURE,
    TYPE_GRAPHQL_INTROSPECTION_RISK,
)

# ---------------------------------------------------------------------------
# Closed hypothesis states
# ---------------------------------------------------------------------------

STATE_WEAKNESS_OBSERVED = "WEAKNESS_OBSERVED"
STATE_CONTROL_PRESENT_OBSERVED = "CONTROL_PRESENT_OBSERVED"
STATE_NEEDS_EVIDENCE = "NEEDS_EVIDENCE"
STATE_NOT_OBSERVED = "NOT_OBSERVED"
STATE_UNKNOWN = "UNKNOWN"

HYPOTHESIS_STATES: tuple[str, ...] = (
    STATE_WEAKNESS_OBSERVED,
    STATE_CONTROL_PRESENT_OBSERVED,
    STATE_NEEDS_EVIDENCE,
    STATE_NOT_OBSERVED,
    STATE_UNKNOWN,
)

# ---------------------------------------------------------------------------
# Closed supporting-signal vocabulary
# ---------------------------------------------------------------------------

# API type / versioning / content type observations.
SIGNAL_API_TYPE_REST = "API_TYPE_REST_OBSERVED"
SIGNAL_API_TYPE_GRAPHQL = "API_TYPE_GRAPHQL_OBSERVED"
SIGNAL_API_TYPE_RPC = "API_TYPE_RPC_OBSERVED"
SIGNAL_API_TYPE_JSON_API = "API_TYPE_JSON_API_OBSERVED"
SIGNAL_API_TYPE_XML_API = "API_TYPE_XML_API_OBSERVED"
SIGNAL_API_TYPE_WEBHOOK = "API_TYPE_WEBHOOK_OBSERVED"
SIGNAL_API_VERSIONED = "API_VERSIONED_OBSERVED"
SIGNAL_API_UNVERSIONED = "API_UNVERSIONED_OBSERVED"
SIGNAL_API_DEPRECATED_VERSION = "API_DEPRECATED_VERSION_OBSERVED"
SIGNAL_CONTENT_TYPE_JSON = "CONTENT_TYPE_JSON_OBSERVED"
SIGNAL_CONTENT_TYPE_FORM = "CONTENT_TYPE_FORM_OBSERVED"
SIGNAL_CONTENT_TYPE_XML = "CONTENT_TYPE_XML_OBSERVED"
SIGNAL_CONTENT_TYPE_MULTIPART = "CONTENT_TYPE_MULTIPART_OBSERVED"

# Authentication mechanism context.
SIGNAL_AUTH_MECHANISM_BEARER_TOKEN = "AUTH_MECHANISM_BEARER_TOKEN_OBSERVED"
SIGNAL_AUTH_MECHANISM_JWT_BEARER = "AUTH_MECHANISM_JWT_BEARER_OBSERVED"
SIGNAL_AUTH_MECHANISM_COOKIE_SESSION = (
    "AUTH_MECHANISM_COOKIE_SESSION_OBSERVED"
)
SIGNAL_AUTH_MECHANISM_OAUTH2 = "AUTH_MECHANISM_OAUTH2_OBSERVED"
SIGNAL_AUTH_MECHANISM_API_KEY = "AUTH_MECHANISM_API_KEY_OBSERVED"
SIGNAL_AUTH_MECHANISM_BASIC = "AUTH_MECHANISM_BASIC_OBSERVED"
SIGNAL_AUTH_MECHANISM_MUTUAL_TLS = "AUTH_MECHANISM_MUTUAL_TLS_OBSERVED"

# API surface observations.
SIGNAL_OBJECT_AUTHORIZATION_CONTEXT_OBSERVED = (
    "OBJECT_AUTHORIZATION_CONTEXT_OBSERVED"
)
SIGNAL_ENDPOINT_METADATA_OBSERVED = "ENDPOINT_METADATA_OBSERVED"
SIGNAL_REQUEST_SCHEMA_OBSERVED = "REQUEST_SCHEMA_OBSERVED"
SIGNAL_RESPONSE_SCHEMA_OBSERVED = "RESPONSE_SCHEMA_OBSERVED"
SIGNAL_PAGINATION_CONTEXT_OBSERVED = "PAGINATION_CONTEXT_OBSERVED"
SIGNAL_BATCH_CONTEXT_OBSERVED = "BATCH_CONTEXT_OBSERVED"
SIGNAL_FILE_UPLOAD_OBSERVED = "FILE_UPLOAD_OBSERVED"
SIGNAL_FILE_DOWNLOAD_OBSERVED = "FILE_DOWNLOAD_OBSERVED"
SIGNAL_NESTED_RESOURCES_OBSERVED = "NESTED_RESOURCES_OBSERVED"
SIGNAL_GRAPHQL_BATCHING_OBSERVED = "GRAPHQL_BATCHING_OBSERVED"
SIGNAL_WEBHOOK_CONTEXT_OBSERVED = "WEBHOOK_CONTEXT_OBSERVED"

# Exposure observations.
SIGNAL_EXCESSIVE_DATA_OBSERVED = "EXCESSIVE_DATA_OBSERVED"
SIGNAL_SENSITIVE_FIELDS_OBSERVED = "SENSITIVE_FIELDS_OBSERVED"
SIGNAL_INTERNAL_IDENTIFIERS_OBSERVED = "INTERNAL_IDENTIFIERS_OBSERVED"
SIGNAL_ERROR_GENERIC_OBSERVED = "ERROR_GENERIC_MESSAGE_OBSERVED"
SIGNAL_ERROR_DETAILED_OBSERVED = "ERROR_DETAILED_OBSERVED"
SIGNAL_ERROR_STACK_TRACE_OBSERVED = "ERROR_STACK_TRACE_OBSERVED"
SIGNAL_DEBUG_INFORMATION_OBSERVED = "DEBUG_INFORMATION_OBSERVED"
SIGNAL_INTROSPECTION_ENABLED_OBSERVED = "INTROSPECTION_ENABLED_OBSERVED"
SIGNAL_INTROSPECTION_DISABLED_OBSERVED = "INTROSPECTION_DISABLED_OBSERVED"

# Validation-control signals: <CONTROL>_{ENFORCED,ABSENT,NOT_PROVIDED}.
SIGNAL_API_AUTHENTICATION_ENFORCED = "API_AUTHENTICATION_ENFORCED_OBSERVED"
SIGNAL_API_AUTHENTICATION_ABSENT = "API_AUTHENTICATION_ABSENT_OBSERVED"
SIGNAL_API_AUTHENTICATION_NOT_PROVIDED = "API_AUTHENTICATION_NOT_PROVIDED"
SIGNAL_ENDPOINT_AUTHORIZATION_ENFORCED = (
    "ENDPOINT_AUTHORIZATION_ENFORCED_OBSERVED"
)
SIGNAL_ENDPOINT_AUTHORIZATION_ABSENT = "ENDPOINT_AUTHORIZATION_ABSENT_OBSERVED"
SIGNAL_ENDPOINT_AUTHORIZATION_NOT_PROVIDED = (
    "ENDPOINT_AUTHORIZATION_NOT_PROVIDED"
)
SIGNAL_FUNCTION_ROLE_AUTHORIZATION_ENFORCED = (
    "FUNCTION_ROLE_AUTHORIZATION_ENFORCED_OBSERVED"
)
SIGNAL_FUNCTION_ROLE_AUTHORIZATION_ABSENT = (
    "FUNCTION_ROLE_AUTHORIZATION_ABSENT_OBSERVED"
)
SIGNAL_FUNCTION_ROLE_AUTHORIZATION_NOT_PROVIDED = (
    "FUNCTION_ROLE_AUTHORIZATION_NOT_PROVIDED"
)
SIGNAL_TENANT_ISOLATION_ENFORCED = "TENANT_ISOLATION_ENFORCED_OBSERVED"
SIGNAL_TENANT_ISOLATION_ABSENT = "TENANT_ISOLATION_ABSENT_OBSERVED"
SIGNAL_TENANT_ISOLATION_NOT_PROVIDED = "TENANT_ISOLATION_NOT_PROVIDED"
SIGNAL_SCHEMA_VALIDATION_ENFORCED = "SCHEMA_VALIDATION_ENFORCED_OBSERVED"
SIGNAL_SCHEMA_VALIDATION_ABSENT = "SCHEMA_VALIDATION_ABSENT_OBSERVED"
SIGNAL_SCHEMA_VALIDATION_NOT_PROVIDED = "SCHEMA_VALIDATION_NOT_PROVIDED"
SIGNAL_PARAMETER_VALIDATION_ENFORCED = "PARAMETER_VALIDATION_ENFORCED_OBSERVED"
SIGNAL_PARAMETER_VALIDATION_ABSENT = "PARAMETER_VALIDATION_ABSENT_OBSERVED"
SIGNAL_PARAMETER_VALIDATION_NOT_PROVIDED = "PARAMETER_VALIDATION_NOT_PROVIDED"
SIGNAL_UNKNOWN_FIELD_HANDLING_ENFORCED = (
    "UNKNOWN_FIELD_HANDLING_ENFORCED_OBSERVED"
)
SIGNAL_UNKNOWN_FIELD_HANDLING_ABSENT = "UNKNOWN_FIELD_HANDLING_ABSENT_OBSERVED"
SIGNAL_UNKNOWN_FIELD_HANDLING_NOT_PROVIDED = (
    "UNKNOWN_FIELD_HANDLING_NOT_PROVIDED"
)
SIGNAL_CONTENT_TYPE_VALIDATION_ENFORCED = (
    "CONTENT_TYPE_VALIDATION_ENFORCED_OBSERVED"
)
SIGNAL_CONTENT_TYPE_VALIDATION_ABSENT = (
    "CONTENT_TYPE_VALIDATION_ABSENT_OBSERVED"
)
SIGNAL_CONTENT_TYPE_VALIDATION_NOT_PROVIDED = (
    "CONTENT_TYPE_VALIDATION_NOT_PROVIDED"
)
SIGNAL_HTTP_METHOD_RESTRICTIONS_ENFORCED = (
    "HTTP_METHOD_RESTRICTIONS_ENFORCED_OBSERVED"
)
SIGNAL_HTTP_METHOD_RESTRICTIONS_ABSENT = (
    "HTTP_METHOD_RESTRICTIONS_ABSENT_OBSERVED"
)
SIGNAL_HTTP_METHOD_RESTRICTIONS_NOT_PROVIDED = (
    "HTTP_METHOD_RESTRICTIONS_NOT_PROVIDED"
)
SIGNAL_METHOD_OVERRIDE_CONTROL_ENFORCED = (
    "METHOD_OVERRIDE_CONTROL_ENFORCED_OBSERVED"
)
SIGNAL_METHOD_OVERRIDE_CONTROL_ABSENT = (
    "METHOD_OVERRIDE_CONTROL_ABSENT_OBSERVED"
)
SIGNAL_METHOD_OVERRIDE_CONTROL_NOT_PROVIDED = (
    "METHOD_OVERRIDE_CONTROL_NOT_PROVIDED"
)
SIGNAL_RATE_LIMIT_CONTROL_ENFORCED = "RATE_LIMIT_CONTROL_ENFORCED_OBSERVED"
SIGNAL_RATE_LIMIT_CONTROL_ABSENT = "RATE_LIMIT_CONTROL_ABSENT_OBSERVED"
SIGNAL_RATE_LIMIT_CONTROL_NOT_PROVIDED = "RATE_LIMIT_CONTROL_NOT_PROVIDED"
SIGNAL_REQUEST_SIZE_LIMIT_ENFORCED = "REQUEST_SIZE_LIMIT_ENFORCED_OBSERVED"
SIGNAL_REQUEST_SIZE_LIMIT_ABSENT = "REQUEST_SIZE_LIMIT_ABSENT_OBSERVED"
SIGNAL_REQUEST_SIZE_LIMIT_NOT_PROVIDED = "REQUEST_SIZE_LIMIT_NOT_PROVIDED"
SIGNAL_PAGINATION_LIMIT_ENFORCED = "PAGINATION_LIMIT_ENFORCED_OBSERVED"
SIGNAL_PAGINATION_LIMIT_ABSENT = "PAGINATION_LIMIT_ABSENT_OBSERVED"
SIGNAL_PAGINATION_LIMIT_NOT_PROVIDED = "PAGINATION_LIMIT_NOT_PROVIDED"
SIGNAL_QUERY_COMPLEXITY_LIMIT_ENFORCED = (
    "QUERY_COMPLEXITY_LIMIT_ENFORCED_OBSERVED"
)
SIGNAL_QUERY_COMPLEXITY_LIMIT_ABSENT = (
    "QUERY_COMPLEXITY_LIMIT_ABSENT_OBSERVED"
)
SIGNAL_QUERY_COMPLEXITY_LIMIT_NOT_PROVIDED = (
    "QUERY_COMPLEXITY_LIMIT_NOT_PROVIDED"
)
SIGNAL_BATCH_LIMIT_ENFORCED = "BATCH_LIMIT_ENFORCED_OBSERVED"
SIGNAL_BATCH_LIMIT_ABSENT = "BATCH_LIMIT_ABSENT_OBSERVED"
SIGNAL_BATCH_LIMIT_NOT_PROVIDED = "BATCH_LIMIT_NOT_PROVIDED"
SIGNAL_UPLOAD_LIMIT_ENFORCED = "UPLOAD_LIMIT_ENFORCED_OBSERVED"
SIGNAL_UPLOAD_LIMIT_ABSENT = "UPLOAD_LIMIT_ABSENT_OBSERVED"
SIGNAL_UPLOAD_LIMIT_NOT_PROVIDED = "UPLOAD_LIMIT_NOT_PROVIDED"
SIGNAL_DOWNLOAD_CONTROL_ENFORCED = "DOWNLOAD_CONTROL_ENFORCED_OBSERVED"
SIGNAL_DOWNLOAD_CONTROL_ABSENT = "DOWNLOAD_CONTROL_ABSENT_OBSERVED"
SIGNAL_DOWNLOAD_CONTROL_NOT_PROVIDED = "DOWNLOAD_CONTROL_NOT_PROVIDED"
SIGNAL_ERROR_DETAIL_CONTROL_ENFORCED = (
    "ERROR_DETAIL_CONTROL_ENFORCED_OBSERVED"
)
SIGNAL_ERROR_DETAIL_CONTROL_ABSENT = "ERROR_DETAIL_CONTROL_ABSENT_OBSERVED"
SIGNAL_ERROR_DETAIL_CONTROL_NOT_PROVIDED = "ERROR_DETAIL_CONTROL_NOT_PROVIDED"
SIGNAL_DEBUG_MODE_CONTROL_ENFORCED = "DEBUG_MODE_CONTROL_ENFORCED_OBSERVED"
SIGNAL_DEBUG_MODE_CONTROL_ABSENT = "DEBUG_MODE_CONTROL_ABSENT_OBSERVED"
SIGNAL_DEBUG_MODE_CONTROL_NOT_PROVIDED = "DEBUG_MODE_CONTROL_NOT_PROVIDED"
SIGNAL_SENSITIVE_FIELD_CONTROL_ENFORCED = (
    "SENSITIVE_FIELD_CONTROL_ENFORCED_OBSERVED"
)
SIGNAL_SENSITIVE_FIELD_CONTROL_ABSENT = (
    "SENSITIVE_FIELD_CONTROL_ABSENT_OBSERVED"
)
SIGNAL_SENSITIVE_FIELD_CONTROL_NOT_PROVIDED = (
    "SENSITIVE_FIELD_CONTROL_NOT_PROVIDED"
)
SIGNAL_CORS_ORIGIN_POLICY_ENFORCED = "CORS_ORIGIN_POLICY_ENFORCED_OBSERVED"
SIGNAL_CORS_ORIGIN_POLICY_ABSENT = "CORS_ORIGIN_POLICY_ABSENT_OBSERVED"
SIGNAL_CORS_ORIGIN_POLICY_NOT_PROVIDED = "CORS_ORIGIN_POLICY_NOT_PROVIDED"
SIGNAL_CORS_CREDENTIALS_POLICY_ENFORCED = (
    "CORS_CREDENTIALS_POLICY_ENFORCED_OBSERVED"
)
SIGNAL_CORS_CREDENTIALS_POLICY_ABSENT = (
    "CORS_CREDENTIALS_POLICY_ABSENT_OBSERVED"
)
SIGNAL_CORS_CREDENTIALS_POLICY_NOT_PROVIDED = (
    "CORS_CREDENTIALS_POLICY_NOT_PROVIDED"
)
SIGNAL_GRAPHQL_FIELD_AUTHORIZATION_ENFORCED = (
    "GRAPHQL_FIELD_AUTHORIZATION_ENFORCED_OBSERVED"
)
SIGNAL_GRAPHQL_FIELD_AUTHORIZATION_ABSENT = (
    "GRAPHQL_FIELD_AUTHORIZATION_ABSENT_OBSERVED"
)
SIGNAL_GRAPHQL_FIELD_AUTHORIZATION_NOT_PROVIDED = (
    "GRAPHQL_FIELD_AUTHORIZATION_NOT_PROVIDED"
)
SIGNAL_GRAPHQL_MUTATION_AUTHORIZATION_ENFORCED = (
    "GRAPHQL_MUTATION_AUTHORIZATION_ENFORCED_OBSERVED"
)
SIGNAL_GRAPHQL_MUTATION_AUTHORIZATION_ABSENT = (
    "GRAPHQL_MUTATION_AUTHORIZATION_ABSENT_OBSERVED"
)
SIGNAL_GRAPHQL_MUTATION_AUTHORIZATION_NOT_PROVIDED = (
    "GRAPHQL_MUTATION_AUTHORIZATION_NOT_PROVIDED"
)
SIGNAL_GRAPHQL_DEPTH_LIMIT_ENFORCED = "GRAPHQL_DEPTH_LIMIT_ENFORCED_OBSERVED"
SIGNAL_GRAPHQL_DEPTH_LIMIT_ABSENT = "GRAPHQL_DEPTH_LIMIT_ABSENT_OBSERVED"
SIGNAL_GRAPHQL_DEPTH_LIMIT_NOT_PROVIDED = "GRAPHQL_DEPTH_LIMIT_NOT_PROVIDED"
SIGNAL_GRAPHQL_COMPLEXITY_LIMIT_ENFORCED = (
    "GRAPHQL_COMPLEXITY_LIMIT_ENFORCED_OBSERVED"
)
SIGNAL_GRAPHQL_COMPLEXITY_LIMIT_ABSENT = (
    "GRAPHQL_COMPLEXITY_LIMIT_ABSENT_OBSERVED"
)
SIGNAL_GRAPHQL_COMPLEXITY_LIMIT_NOT_PROVIDED = (
    "GRAPHQL_COMPLEXITY_LIMIT_NOT_PROVIDED"
)
SIGNAL_GRAPHQL_INTROSPECTION_CONTROL_ENFORCED = (
    "GRAPHQL_INTROSPECTION_CONTROL_ENFORCED_OBSERVED"
)
SIGNAL_GRAPHQL_INTROSPECTION_CONTROL_ABSENT = (
    "GRAPHQL_INTROSPECTION_CONTROL_ABSENT_OBSERVED"
)
SIGNAL_GRAPHQL_INTROSPECTION_CONTROL_NOT_PROVIDED = (
    "GRAPHQL_INTROSPECTION_CONTROL_NOT_PROVIDED"
)
SIGNAL_API_KEY_ROTATION_ENFORCED = "API_KEY_ROTATION_ENFORCED_OBSERVED"
SIGNAL_API_KEY_ROTATION_ABSENT = "API_KEY_ROTATION_ABSENT_OBSERVED"
SIGNAL_API_KEY_ROTATION_NOT_PROVIDED = "API_KEY_ROTATION_NOT_PROVIDED"
SIGNAL_API_KEY_REVOCATION_ENFORCED = "API_KEY_REVOCATION_ENFORCED_OBSERVED"
SIGNAL_API_KEY_REVOCATION_ABSENT = "API_KEY_REVOCATION_ABSENT_OBSERVED"
SIGNAL_API_KEY_REVOCATION_NOT_PROVIDED = "API_KEY_REVOCATION_NOT_PROVIDED"
SIGNAL_WEBHOOK_SIGNATURE_VALIDATION_ENFORCED = (
    "WEBHOOK_SIGNATURE_VALIDATION_ENFORCED_OBSERVED"
)
SIGNAL_WEBHOOK_SIGNATURE_VALIDATION_ABSENT = (
    "WEBHOOK_SIGNATURE_VALIDATION_ABSENT_OBSERVED"
)
SIGNAL_WEBHOOK_SIGNATURE_VALIDATION_NOT_PROVIDED = (
    "WEBHOOK_SIGNATURE_VALIDATION_NOT_PROVIDED"
)
SIGNAL_WEBHOOK_REPLAY_PROTECTION_ENFORCED = (
    "WEBHOOK_REPLAY_PROTECTION_ENFORCED_OBSERVED"
)
SIGNAL_WEBHOOK_REPLAY_PROTECTION_ABSENT = (
    "WEBHOOK_REPLAY_PROTECTION_ABSENT_OBSERVED"
)
SIGNAL_WEBHOOK_REPLAY_PROTECTION_NOT_PROVIDED = (
    "WEBHOOK_REPLAY_PROTECTION_NOT_PROVIDED"
)
SIGNAL_WEBHOOK_SOURCE_VALIDATION_ENFORCED = (
    "WEBHOOK_SOURCE_VALIDATION_ENFORCED_OBSERVED"
)
SIGNAL_WEBHOOK_SOURCE_VALIDATION_ABSENT = (
    "WEBHOOK_SOURCE_VALIDATION_ABSENT_OBSERVED"
)
SIGNAL_WEBHOOK_SOURCE_VALIDATION_NOT_PROVIDED = (
    "WEBHOOK_SOURCE_VALIDATION_NOT_PROVIDED"
)

SIGNAL_MISSING_API_CONTEXT = "MISSING_API_CONTEXT"
SIGNAL_CONTEXT_UNKNOWN = "CONTEXT_UNKNOWN"

API_SECURITY_SIGNALS: tuple[str, ...] = (
    SIGNAL_API_TYPE_REST,
    SIGNAL_API_TYPE_GRAPHQL,
    SIGNAL_API_TYPE_RPC,
    SIGNAL_API_TYPE_JSON_API,
    SIGNAL_API_TYPE_XML_API,
    SIGNAL_API_TYPE_WEBHOOK,
    SIGNAL_API_VERSIONED,
    SIGNAL_API_UNVERSIONED,
    SIGNAL_API_DEPRECATED_VERSION,
    SIGNAL_CONTENT_TYPE_JSON,
    SIGNAL_CONTENT_TYPE_FORM,
    SIGNAL_CONTENT_TYPE_XML,
    SIGNAL_CONTENT_TYPE_MULTIPART,
    SIGNAL_AUTH_MECHANISM_BEARER_TOKEN,
    SIGNAL_AUTH_MECHANISM_JWT_BEARER,
    SIGNAL_AUTH_MECHANISM_COOKIE_SESSION,
    SIGNAL_AUTH_MECHANISM_OAUTH2,
    SIGNAL_AUTH_MECHANISM_API_KEY,
    SIGNAL_AUTH_MECHANISM_BASIC,
    SIGNAL_AUTH_MECHANISM_MUTUAL_TLS,
    SIGNAL_OBJECT_AUTHORIZATION_CONTEXT_OBSERVED,
    SIGNAL_ENDPOINT_METADATA_OBSERVED,
    SIGNAL_REQUEST_SCHEMA_OBSERVED,
    SIGNAL_RESPONSE_SCHEMA_OBSERVED,
    SIGNAL_PAGINATION_CONTEXT_OBSERVED,
    SIGNAL_BATCH_CONTEXT_OBSERVED,
    SIGNAL_FILE_UPLOAD_OBSERVED,
    SIGNAL_FILE_DOWNLOAD_OBSERVED,
    SIGNAL_NESTED_RESOURCES_OBSERVED,
    SIGNAL_GRAPHQL_BATCHING_OBSERVED,
    SIGNAL_WEBHOOK_CONTEXT_OBSERVED,
    SIGNAL_EXCESSIVE_DATA_OBSERVED,
    SIGNAL_SENSITIVE_FIELDS_OBSERVED,
    SIGNAL_INTERNAL_IDENTIFIERS_OBSERVED,
    SIGNAL_ERROR_GENERIC_OBSERVED,
    SIGNAL_ERROR_DETAILED_OBSERVED,
    SIGNAL_ERROR_STACK_TRACE_OBSERVED,
    SIGNAL_DEBUG_INFORMATION_OBSERVED,
    SIGNAL_INTROSPECTION_ENABLED_OBSERVED,
    SIGNAL_INTROSPECTION_DISABLED_OBSERVED,
    SIGNAL_API_AUTHENTICATION_ENFORCED,
    SIGNAL_API_AUTHENTICATION_ABSENT,
    SIGNAL_API_AUTHENTICATION_NOT_PROVIDED,
    SIGNAL_ENDPOINT_AUTHORIZATION_ENFORCED,
    SIGNAL_ENDPOINT_AUTHORIZATION_ABSENT,
    SIGNAL_ENDPOINT_AUTHORIZATION_NOT_PROVIDED,
    SIGNAL_FUNCTION_ROLE_AUTHORIZATION_ENFORCED,
    SIGNAL_FUNCTION_ROLE_AUTHORIZATION_ABSENT,
    SIGNAL_FUNCTION_ROLE_AUTHORIZATION_NOT_PROVIDED,
    SIGNAL_TENANT_ISOLATION_ENFORCED,
    SIGNAL_TENANT_ISOLATION_ABSENT,
    SIGNAL_TENANT_ISOLATION_NOT_PROVIDED,
    SIGNAL_SCHEMA_VALIDATION_ENFORCED,
    SIGNAL_SCHEMA_VALIDATION_ABSENT,
    SIGNAL_SCHEMA_VALIDATION_NOT_PROVIDED,
    SIGNAL_PARAMETER_VALIDATION_ENFORCED,
    SIGNAL_PARAMETER_VALIDATION_ABSENT,
    SIGNAL_PARAMETER_VALIDATION_NOT_PROVIDED,
    SIGNAL_UNKNOWN_FIELD_HANDLING_ENFORCED,
    SIGNAL_UNKNOWN_FIELD_HANDLING_ABSENT,
    SIGNAL_UNKNOWN_FIELD_HANDLING_NOT_PROVIDED,
    SIGNAL_CONTENT_TYPE_VALIDATION_ENFORCED,
    SIGNAL_CONTENT_TYPE_VALIDATION_ABSENT,
    SIGNAL_CONTENT_TYPE_VALIDATION_NOT_PROVIDED,
    SIGNAL_HTTP_METHOD_RESTRICTIONS_ENFORCED,
    SIGNAL_HTTP_METHOD_RESTRICTIONS_ABSENT,
    SIGNAL_HTTP_METHOD_RESTRICTIONS_NOT_PROVIDED,
    SIGNAL_METHOD_OVERRIDE_CONTROL_ENFORCED,
    SIGNAL_METHOD_OVERRIDE_CONTROL_ABSENT,
    SIGNAL_METHOD_OVERRIDE_CONTROL_NOT_PROVIDED,
    SIGNAL_RATE_LIMIT_CONTROL_ENFORCED,
    SIGNAL_RATE_LIMIT_CONTROL_ABSENT,
    SIGNAL_RATE_LIMIT_CONTROL_NOT_PROVIDED,
    SIGNAL_REQUEST_SIZE_LIMIT_ENFORCED,
    SIGNAL_REQUEST_SIZE_LIMIT_ABSENT,
    SIGNAL_REQUEST_SIZE_LIMIT_NOT_PROVIDED,
    SIGNAL_PAGINATION_LIMIT_ENFORCED,
    SIGNAL_PAGINATION_LIMIT_ABSENT,
    SIGNAL_PAGINATION_LIMIT_NOT_PROVIDED,
    SIGNAL_QUERY_COMPLEXITY_LIMIT_ENFORCED,
    SIGNAL_QUERY_COMPLEXITY_LIMIT_ABSENT,
    SIGNAL_QUERY_COMPLEXITY_LIMIT_NOT_PROVIDED,
    SIGNAL_BATCH_LIMIT_ENFORCED,
    SIGNAL_BATCH_LIMIT_ABSENT,
    SIGNAL_BATCH_LIMIT_NOT_PROVIDED,
    SIGNAL_UPLOAD_LIMIT_ENFORCED,
    SIGNAL_UPLOAD_LIMIT_ABSENT,
    SIGNAL_UPLOAD_LIMIT_NOT_PROVIDED,
    SIGNAL_DOWNLOAD_CONTROL_ENFORCED,
    SIGNAL_DOWNLOAD_CONTROL_ABSENT,
    SIGNAL_DOWNLOAD_CONTROL_NOT_PROVIDED,
    SIGNAL_ERROR_DETAIL_CONTROL_ENFORCED,
    SIGNAL_ERROR_DETAIL_CONTROL_ABSENT,
    SIGNAL_ERROR_DETAIL_CONTROL_NOT_PROVIDED,
    SIGNAL_DEBUG_MODE_CONTROL_ENFORCED,
    SIGNAL_DEBUG_MODE_CONTROL_ABSENT,
    SIGNAL_DEBUG_MODE_CONTROL_NOT_PROVIDED,
    SIGNAL_SENSITIVE_FIELD_CONTROL_ENFORCED,
    SIGNAL_SENSITIVE_FIELD_CONTROL_ABSENT,
    SIGNAL_SENSITIVE_FIELD_CONTROL_NOT_PROVIDED,
    SIGNAL_CORS_ORIGIN_POLICY_ENFORCED,
    SIGNAL_CORS_ORIGIN_POLICY_ABSENT,
    SIGNAL_CORS_ORIGIN_POLICY_NOT_PROVIDED,
    SIGNAL_CORS_CREDENTIALS_POLICY_ENFORCED,
    SIGNAL_CORS_CREDENTIALS_POLICY_ABSENT,
    SIGNAL_CORS_CREDENTIALS_POLICY_NOT_PROVIDED,
    SIGNAL_GRAPHQL_FIELD_AUTHORIZATION_ENFORCED,
    SIGNAL_GRAPHQL_FIELD_AUTHORIZATION_ABSENT,
    SIGNAL_GRAPHQL_FIELD_AUTHORIZATION_NOT_PROVIDED,
    SIGNAL_GRAPHQL_MUTATION_AUTHORIZATION_ENFORCED,
    SIGNAL_GRAPHQL_MUTATION_AUTHORIZATION_ABSENT,
    SIGNAL_GRAPHQL_MUTATION_AUTHORIZATION_NOT_PROVIDED,
    SIGNAL_GRAPHQL_DEPTH_LIMIT_ENFORCED,
    SIGNAL_GRAPHQL_DEPTH_LIMIT_ABSENT,
    SIGNAL_GRAPHQL_DEPTH_LIMIT_NOT_PROVIDED,
    SIGNAL_GRAPHQL_COMPLEXITY_LIMIT_ENFORCED,
    SIGNAL_GRAPHQL_COMPLEXITY_LIMIT_ABSENT,
    SIGNAL_GRAPHQL_COMPLEXITY_LIMIT_NOT_PROVIDED,
    SIGNAL_GRAPHQL_INTROSPECTION_CONTROL_ENFORCED,
    SIGNAL_GRAPHQL_INTROSPECTION_CONTROL_ABSENT,
    SIGNAL_GRAPHQL_INTROSPECTION_CONTROL_NOT_PROVIDED,
    SIGNAL_API_KEY_ROTATION_ENFORCED,
    SIGNAL_API_KEY_ROTATION_ABSENT,
    SIGNAL_API_KEY_ROTATION_NOT_PROVIDED,
    SIGNAL_API_KEY_REVOCATION_ENFORCED,
    SIGNAL_API_KEY_REVOCATION_ABSENT,
    SIGNAL_API_KEY_REVOCATION_NOT_PROVIDED,
    SIGNAL_WEBHOOK_SIGNATURE_VALIDATION_ENFORCED,
    SIGNAL_WEBHOOK_SIGNATURE_VALIDATION_ABSENT,
    SIGNAL_WEBHOOK_SIGNATURE_VALIDATION_NOT_PROVIDED,
    SIGNAL_WEBHOOK_REPLAY_PROTECTION_ENFORCED,
    SIGNAL_WEBHOOK_REPLAY_PROTECTION_ABSENT,
    SIGNAL_WEBHOOK_REPLAY_PROTECTION_NOT_PROVIDED,
    SIGNAL_WEBHOOK_SOURCE_VALIDATION_ENFORCED,
    SIGNAL_WEBHOOK_SOURCE_VALIDATION_ABSENT,
    SIGNAL_WEBHOOK_SOURCE_VALIDATION_NOT_PROVIDED,
    SIGNAL_MISSING_API_CONTEXT,
    SIGNAL_CONTEXT_UNKNOWN,
)

# ---------------------------------------------------------------------------
# Closed limitations
# ---------------------------------------------------------------------------

LIMITATION_NO_EXPLOIT_CLAIM = "NO_EXPLOIT_CLAIM"
LIMITATION_NO_VULNERABILITY_CONFIRMATION = "NO_VULNERABILITY_CONFIRMATION"
LIMITATION_NO_API_ATTACK_CLAIM = "NO_API_ATTACK_CLAIM"
LIMITATION_NO_AUTH_BYPASS_CLAIM = "NO_AUTH_BYPASS_CLAIM"
LIMITATION_NO_IDOR_EXPLOIT_CLAIM = "NO_IDOR_EXPLOIT_CLAIM"
LIMITATION_NO_INJECTION_EXPLOIT_CLAIM = "NO_INJECTION_EXPLOIT_CLAIM"
LIMITATION_HYPOTHESIS_ONLY = "HYPOTHESIS_ONLY"
LIMITATION_EVIDENCE_REQUIRED = "EVIDENCE_REQUIRED"
LIMITATION_INSUFFICIENT_CONTEXT = "INSUFFICIENT_CONTEXT"

API_SECURITY_HYPOTHESIS_LIMITATIONS: tuple[str, ...] = (
    LIMITATION_NO_EXPLOIT_CLAIM,
    LIMITATION_NO_VULNERABILITY_CONFIRMATION,
    LIMITATION_NO_API_ATTACK_CLAIM,
    LIMITATION_NO_AUTH_BYPASS_CLAIM,
    LIMITATION_NO_IDOR_EXPLOIT_CLAIM,
    LIMITATION_NO_INJECTION_EXPLOIT_CLAIM,
    LIMITATION_HYPOTHESIS_ONLY,
    LIMITATION_EVIDENCE_REQUIRED,
    LIMITATION_INSUFFICIENT_CONTEXT,
)

MAX_SIGNALS = 12
MAX_LIMITATIONS = 9
MAX_VALUE_LEN = 160
MAX_RATIONALE_LEN = 240

_CONTROL_RE = re.compile(r"[\x00-\x1f\x7f]+")


def _safe_text(value: object, limit: int = MAX_VALUE_LEN) -> str:
    text = _CONTROL_RE.sub(" ", str(value if value is not None else ""))
    return " ".join(text.split())[:limit]


def _require_codes(value: object, allowed: tuple, limit: int) -> list[str]:
    out: list[str] = []
    for item in value or ():
        text = _safe_text(item)
        if not text:
            continue
        if text not in allowed:
            raise ValueError(f"invalid closed code: {text!r}")
        if text not in out:
            out.append(text)
        if len(out) >= limit:
            break
    return out


def sanitize_api_security_hypothesis_plan(value: object) -> dict:
    """Project an R49.3 hypothesis onto its fixed bounded key set."""

    if not isinstance(value, dict):
        return {
            "rule_version": "",
            "hypothesis_type": TYPE_UNKNOWN,
            "hypothesis_state": STATE_UNKNOWN,
            "supporting_signals": [],
            "confidence": "UNKNOWN",
            "priority": "UNKNOWN",
            "rationale": "",
            "limitations": [],
            "research_only": True,
        }
    hypothesis_type = _safe_text(
        value.get("hypothesis_type")
    ).strip().upper()
    if hypothesis_type not in HYPOTHESIS_TYPES:
        hypothesis_type = TYPE_UNKNOWN
    hypothesis_state = _safe_text(
        value.get("hypothesis_state")
    ).strip().upper()
    if hypothesis_state not in HYPOTHESIS_STATES:
        hypothesis_state = STATE_UNKNOWN
    confidence = _safe_text(value.get("confidence")).strip().upper()
    if confidence not in CONFIDENCE_LEVELS:
        confidence = "UNKNOWN"
    priority = _safe_text(value.get("priority")).strip().upper()
    if priority not in CONFIDENCE_LEVELS:
        priority = "UNKNOWN"
    return {
        "rule_version": _safe_text(value.get("rule_version")),
        "hypothesis_type": hypothesis_type,
        "hypothesis_state": hypothesis_state,
        "supporting_signals": [
            signal
            for signal in (
                _safe_text(item)
                for item in value.get("supporting_signals") or ()
            )
            if signal in API_SECURITY_SIGNALS
        ][:MAX_SIGNALS],
        "confidence": confidence,
        "priority": priority,
        "rationale": _safe_text(value.get("rationale"), MAX_RATIONALE_LEN),
        "limitations": [
            code
            for code in (
                _safe_text(item) for item in value.get("limitations") or ()
            )
            if code in API_SECURITY_HYPOTHESIS_LIMITATIONS
        ][:MAX_LIMITATIONS],
        "research_only": True,
    }


# ---------------------------------------------------------------------------
# Model
# ---------------------------------------------------------------------------


class APISecurityHypothesisPlan(BaseModel):
    """Deterministic research-only API security hypothesis (R49.3)."""

    model_config = ConfigDict(extra="forbid")

    rule_version: str = API_SECURITY_HYPOTHESIS_RULE_VERSION
    hypothesis_type: str
    hypothesis_state: str = STATE_UNKNOWN
    supporting_signals: list[str] = Field(default_factory=list)
    confidence: str = "UNKNOWN"
    priority: str = "UNKNOWN"
    rationale: str = ""
    limitations: list[str] = Field(default_factory=list)
    research_only: bool = True

    @field_validator("rule_version")
    @classmethod
    def _fixed_rule(cls, value: object) -> str:
        return API_SECURITY_HYPOTHESIS_RULE_VERSION

    @field_validator("hypothesis_type")
    @classmethod
    def _valid_type(cls, value: object) -> str:
        text = _safe_text(value).strip().upper()
        if text not in HYPOTHESIS_TYPES:
            raise ValueError(f"invalid hypothesis_type: {value!r}")
        return text

    @field_validator("hypothesis_state")
    @classmethod
    def _valid_state(cls, value: object) -> str:
        text = _safe_text(value).strip().upper()
        if text not in HYPOTHESIS_STATES:
            raise ValueError(f"invalid hypothesis_state: {value!r}")
        return text

    @field_validator("supporting_signals")
    @classmethod
    def _valid_signals(cls, value: list) -> list[str]:
        return _require_codes(value, API_SECURITY_SIGNALS, MAX_SIGNALS)

    @field_validator("confidence", "priority")
    @classmethod
    def _valid_confidence(cls, value: object) -> str:
        text = _safe_text(value).strip().upper()
        if text not in CONFIDENCE_LEVELS:
            raise ValueError(f"invalid confidence/priority: {value!r}")
        return text

    @field_validator("rationale")
    @classmethod
    def _bounded_rationale(cls, value: object) -> str:
        return _safe_text(value, MAX_RATIONALE_LEN)

    @field_validator("limitations")
    @classmethod
    def _valid_limitations(cls, value: list) -> list[str]:
        return _require_codes(
            value, API_SECURITY_HYPOTHESIS_LIMITATIONS, MAX_LIMITATIONS
        )

    @field_validator("research_only")
    @classmethod
    def _research_only(cls, value: object) -> bool:
        if not value:
            raise ValueError("api security hypotheses are research-only")
        return True


def api_security_hypothesis_plan_projection(
    value: APISecurityHypothesisPlan,
) -> dict:
    """Serialize an R49.3 hypothesis to a deterministic dict."""

    return value.model_dump(mode="json")


__all__ = [
    "API_SECURITY_HYPOTHESIS_RULE_VERSION",
    "RULE_VERSION",
    "TYPE_API_AUTHENTICATION_GAP",
    "TYPE_API_AUTHORIZATION_GAP",
    "TYPE_FUNCTION_LEVEL_AUTHORIZATION_GAP",
    "TYPE_TENANT_ISOLATION_GAP",
    "TYPE_INPUT_VALIDATION_GAP",
    "TYPE_SCHEMA_VALIDATION_GAP",
    "TYPE_MASS_ASSIGNMENT_RISK",
    "TYPE_HTTP_METHOD_CONTROL_GAP",
    "TYPE_METHOD_OVERRIDE_RISK",
    "TYPE_API_VERSIONING_RISK",
    "TYPE_RESOURCE_EXPOSURE_RISK",
    "TYPE_SENSITIVE_FIELD_EXPOSURE_RISK",
    "TYPE_ERROR_INFORMATION_DISCLOSURE",
    "TYPE_DEBUG_INFORMATION_EXPOSURE",
    "TYPE_RATE_LIMIT_CONTROL_GAP",
    "TYPE_RESOURCE_LIMIT_CONTROL_GAP",
    "TYPE_PAGINATION_CONTROL_GAP",
    "TYPE_QUERY_COMPLEXITY_CONTROL_GAP",
    "TYPE_BATCH_OPERATION_CONTROL_GAP",
    "TYPE_FILE_UPLOAD_CONTROL_GAP",
    "TYPE_FILE_DOWNLOAD_CONTROL_GAP",
    "TYPE_CORS_CONTROL_GAP",
    "TYPE_GRAPHQL_INTROSPECTION_RISK",
    "TYPE_GRAPHQL_AUTHORIZATION_GAP",
    "TYPE_GRAPHQL_QUERY_COMPLEXITY_GAP",
    "TYPE_API_KEY_CONTROL_GAP",
    "TYPE_WEBHOOK_SIGNATURE_CONTROL_GAP",
    "TYPE_WEBHOOK_REPLAY_CONTROL_GAP",
    "TYPE_CONTENT_TYPE_CONTROL_GAP",
    "TYPE_API_SECURITY_CONTROL_PRESENT",
    "TYPE_MISSING_API_CONTEXT",
    "TYPE_UNKNOWN",
    "HYPOTHESIS_TYPES",
    "VALIDATION_GAP_HYPOTHESIS_TYPES",
    "RISK_HYPOTHESIS_TYPES",
    "STATE_WEAKNESS_OBSERVED",
    "STATE_CONTROL_PRESENT_OBSERVED",
    "STATE_NEEDS_EVIDENCE",
    "STATE_NOT_OBSERVED",
    "STATE_UNKNOWN",
    "HYPOTHESIS_STATES",
    "API_SECURITY_SIGNALS",
    "LIMITATION_NO_EXPLOIT_CLAIM",
    "LIMITATION_NO_VULNERABILITY_CONFIRMATION",
    "LIMITATION_NO_API_ATTACK_CLAIM",
    "LIMITATION_NO_AUTH_BYPASS_CLAIM",
    "LIMITATION_NO_IDOR_EXPLOIT_CLAIM",
    "LIMITATION_NO_INJECTION_EXPLOIT_CLAIM",
    "LIMITATION_HYPOTHESIS_ONLY",
    "LIMITATION_EVIDENCE_REQUIRED",
    "LIMITATION_INSUFFICIENT_CONTEXT",
    "API_SECURITY_HYPOTHESIS_LIMITATIONS",
    "MAX_SIGNALS",
    "MAX_LIMITATIONS",
    "MAX_VALUE_LEN",
    "MAX_RATIONALE_LEN",
    "sanitize_api_security_hypothesis_plan",
    "APISecurityHypothesisPlan",
    "api_security_hypothesis_plan_projection",
]
