"""JWT/authentication hypothesis schema (Stage R47.3).

A :class:`JWTAuthenticationHypothesisPlan` is a deterministic research
hypothesis about possible authentication/JWT validation or control behavior.
It answers the research question:

    "Which authentication/JWT research hypothesis follows from the supplied
     context?"

Hard boundaries encoded here:

- Research hypothesis only: no exploit claim, no vulnerability confirmation,
  no signature bypass, no authentication bypass, no token forgery, no
  credential testing, no payload, no attack sequence, no execution.
- Technology presence is never a hypothesis of weakness by itself.
- Closed vocabularies: hypothesis type, hypothesis state, supporting signals,
  confidence, priority, rationale and limitations are closed/bounded.
- Confidence and priority reuse the shared evidence-confidence vocabulary.
  Priority means "how useful is further research of this authentication
  hypothesis?"; it is NOT severity, exploitability, CVSS or vulnerability
  probability.
- ``hypothesis_state`` explicitly distinguishes an observed control, an
  observed weakness, a not-observed signal and a need for evidence.
- Bounded, privacy-safe, JSON serializable.

No I/O, no network, no LLM, no Mongo, no execution of any kind is represented
here.
"""

from __future__ import annotations

import re

from pydantic import BaseModel, ConfigDict, Field, field_validator

from ai.schemas.evidence_confidence import CONFIDENCE_LEVELS

JWT_AUTHENTICATION_HYPOTHESIS_RULE_VERSION = "r47-3"
RULE_VERSION = JWT_AUTHENTICATION_HYPOTHESIS_RULE_VERSION

# ---------------------------------------------------------------------------
# Closed hypothesis vocabulary
# ---------------------------------------------------------------------------

TYPE_JWT_VALIDATION_GAP = "JWT_VALIDATION_GAP"
TYPE_SIGNATURE_VERIFICATION_GAP = "SIGNATURE_VERIFICATION_GAP"
TYPE_ALGORITHM_VALIDATION_GAP = "ALGORITHM_VALIDATION_GAP"
TYPE_CLAIM_VALIDATION_GAP = "CLAIM_VALIDATION_GAP"
TYPE_ISSUER_VALIDATION_GAP = "ISSUER_VALIDATION_GAP"
TYPE_AUDIENCE_VALIDATION_GAP = "AUDIENCE_VALIDATION_GAP"
TYPE_EXPIRATION_VALIDATION_GAP = "EXPIRATION_VALIDATION_GAP"
TYPE_NOT_BEFORE_VALIDATION_GAP = "NOT_BEFORE_VALIDATION_GAP"
TYPE_KEY_MANAGEMENT_GAP = "KEY_MANAGEMENT_GAP"
TYPE_TOKEN_LIFETIME_RISK = "TOKEN_LIFETIME_RISK"
TYPE_TOKEN_STORAGE_RISK = "TOKEN_STORAGE_RISK"
TYPE_TOKEN_REVOCATION_GAP = "TOKEN_REVOCATION_GAP"
TYPE_REFRESH_TOKEN_CONTROL_GAP = "REFRESH_TOKEN_CONTROL_GAP"
TYPE_SESSION_MANAGEMENT_GAP = "SESSION_MANAGEMENT_GAP"
TYPE_AUTHENTICATION_FLOW_GAP = "AUTHENTICATION_FLOW_GAP"
TYPE_AUTHENTICATION_CONTROL_PRESENT = "AUTHENTICATION_CONTROL_PRESENT"
TYPE_MISSING_AUTHENTICATION_CONTEXT = "MISSING_AUTHENTICATION_CONTEXT"
TYPE_UNKNOWN = "UNKNOWN"

HYPOTHESIS_TYPES: tuple[str, ...] = (
    TYPE_JWT_VALIDATION_GAP,
    TYPE_SIGNATURE_VERIFICATION_GAP,
    TYPE_ALGORITHM_VALIDATION_GAP,
    TYPE_CLAIM_VALIDATION_GAP,
    TYPE_ISSUER_VALIDATION_GAP,
    TYPE_AUDIENCE_VALIDATION_GAP,
    TYPE_EXPIRATION_VALIDATION_GAP,
    TYPE_NOT_BEFORE_VALIDATION_GAP,
    TYPE_KEY_MANAGEMENT_GAP,
    TYPE_TOKEN_LIFETIME_RISK,
    TYPE_TOKEN_STORAGE_RISK,
    TYPE_TOKEN_REVOCATION_GAP,
    TYPE_REFRESH_TOKEN_CONTROL_GAP,
    TYPE_SESSION_MANAGEMENT_GAP,
    TYPE_AUTHENTICATION_FLOW_GAP,
    TYPE_AUTHENTICATION_CONTROL_PRESENT,
    TYPE_MISSING_AUTHENTICATION_CONTEXT,
    TYPE_UNKNOWN,
)

VALIDATION_GAP_HYPOTHESIS_TYPES: tuple[str, ...] = (
    TYPE_JWT_VALIDATION_GAP,
    TYPE_SIGNATURE_VERIFICATION_GAP,
    TYPE_ALGORITHM_VALIDATION_GAP,
    TYPE_CLAIM_VALIDATION_GAP,
    TYPE_ISSUER_VALIDATION_GAP,
    TYPE_AUDIENCE_VALIDATION_GAP,
    TYPE_EXPIRATION_VALIDATION_GAP,
    TYPE_NOT_BEFORE_VALIDATION_GAP,
)

CONTROL_GAP_HYPOTHESIS_TYPES: tuple[str, ...] = (
    TYPE_KEY_MANAGEMENT_GAP,
    TYPE_TOKEN_LIFETIME_RISK,
    TYPE_TOKEN_STORAGE_RISK,
    TYPE_TOKEN_REVOCATION_GAP,
    TYPE_REFRESH_TOKEN_CONTROL_GAP,
    TYPE_SESSION_MANAGEMENT_GAP,
    TYPE_AUTHENTICATION_FLOW_GAP,
)

# ---------------------------------------------------------------------------
# Closed hypothesis states
# ---------------------------------------------------------------------------

STATE_WEAKNESS_OBSERVED = "WEAKNESS_OBSERVED"
STATE_CONTROL_PRESENT_OBSERVED = "CONTROL_PRESENT_OBSERVED"
STATE_NEEDS_EVIDENCE = "NEEDS_EVIDENCE"
STATE_NOT_OBSERVED = "NOT_OBSERVED"
STATE_UNKNOWN = "UNKNOWN"

HYPOTHESIS_STATES: tuple[str, ...] = (
    STATE_WEAKNESS_OBSERVED,
    STATE_CONTROL_PRESENT_OBSERVED,
    STATE_NEEDS_EVIDENCE,
    STATE_NOT_OBSERVED,
    STATE_UNKNOWN,
)

# ---------------------------------------------------------------------------
# Closed supporting-signal vocabulary
# ---------------------------------------------------------------------------

SIGNAL_AUTH_MECHANISM_NONE_OBSERVED = "AUTH_MECHANISM_NONE_OBSERVED"
SIGNAL_AUTH_MECHANISM_BEARER_TOKEN = "AUTH_MECHANISM_BEARER_TOKEN"
SIGNAL_AUTH_MECHANISM_JWT_BEARER = "AUTH_MECHANISM_JWT_BEARER"
SIGNAL_AUTH_MECHANISM_COOKIE_SESSION = "AUTH_MECHANISM_COOKIE_SESSION"
SIGNAL_AUTH_MECHANISM_OAUTH2 = "AUTH_MECHANISM_OAUTH2"
SIGNAL_AUTH_MECHANISM_API_KEY = "AUTH_MECHANISM_API_KEY"
SIGNAL_AUTH_MECHANISM_BASIC = "AUTH_MECHANISM_BASIC"
SIGNAL_AUTH_MECHANISM_MUTUAL_TLS = "AUTH_MECHANISM_MUTUAL_TLS"
SIGNAL_TOKEN_MECHANISM_JWT = "TOKEN_MECHANISM_JWT"
SIGNAL_TOKEN_MECHANISM_OPAQUE_ACCESS = "TOKEN_MECHANISM_OPAQUE_ACCESS"
SIGNAL_TOKEN_MECHANISM_REFRESH = "TOKEN_MECHANISM_REFRESH"
SIGNAL_TOKEN_MECHANISM_SESSION_COOKIE = "TOKEN_MECHANISM_SESSION_COOKIE"
SIGNAL_TOKEN_MECHANISM_NONE_OBSERVED = "TOKEN_MECHANISM_NONE_OBSERVED"
SIGNAL_JWT_FORMAT_COMPACT_JWS = "JWT_FORMAT_COMPACT_JWS"
SIGNAL_JWT_FORMAT_COMPACT_JWE = "JWT_FORMAT_COMPACT_JWE"
SIGNAL_SIGNING_ALGORITHM_METADATA_PRESENT = (
    "SIGNING_ALGORITHM_METADATA_PRESENT"
)
SIGNAL_SIGNING_ALGORITHM_NONE_OBSERVED = "SIGNING_ALGORITHM_NONE_OBSERVED"
SIGNAL_SIGNING_METHOD_SYMMETRIC = "SIGNING_METHOD_SYMMETRIC"
SIGNAL_SIGNING_METHOD_ASYMMETRIC = "SIGNING_METHOD_ASYMMETRIC"
SIGNAL_SIGNATURE_VERIFICATION_ENFORCED = (
    "SIGNATURE_VERIFICATION_ENFORCED_OBSERVED"
)
SIGNAL_SIGNATURE_VERIFICATION_ABSENT = (
    "SIGNATURE_VERIFICATION_ABSENT_OBSERVED"
)
SIGNAL_SIGNATURE_VERIFICATION_NOT_PROVIDED = (
    "SIGNATURE_VERIFICATION_NOT_PROVIDED"
)
SIGNAL_ALGORITHM_VALIDATION_ENFORCED = (
    "ALGORITHM_VALIDATION_ENFORCED_OBSERVED"
)
SIGNAL_ALGORITHM_VALIDATION_ABSENT = "ALGORITHM_VALIDATION_ABSENT_OBSERVED"
SIGNAL_ALGORITHM_VALIDATION_NOT_PROVIDED = (
    "ALGORITHM_VALIDATION_NOT_PROVIDED"
)
SIGNAL_ISSUER_VALIDATION_ENFORCED = "ISSUER_VALIDATION_ENFORCED_OBSERVED"
SIGNAL_ISSUER_VALIDATION_ABSENT = "ISSUER_VALIDATION_ABSENT_OBSERVED"
SIGNAL_ISSUER_VALIDATION_NOT_PROVIDED = "ISSUER_VALIDATION_NOT_PROVIDED"
SIGNAL_AUDIENCE_VALIDATION_ENFORCED = (
    "AUDIENCE_VALIDATION_ENFORCED_OBSERVED"
)
SIGNAL_AUDIENCE_VALIDATION_ABSENT = "AUDIENCE_VALIDATION_ABSENT_OBSERVED"
SIGNAL_AUDIENCE_VALIDATION_NOT_PROVIDED = (
    "AUDIENCE_VALIDATION_NOT_PROVIDED"
)
SIGNAL_EXPIRATION_VALIDATION_ENFORCED = (
    "EXPIRATION_VALIDATION_ENFORCED_OBSERVED"
)
SIGNAL_EXPIRATION_VALIDATION_ABSENT = (
    "EXPIRATION_VALIDATION_ABSENT_OBSERVED"
)
SIGNAL_EXPIRATION_VALIDATION_NOT_PROVIDED = (
    "EXPIRATION_VALIDATION_NOT_PROVIDED"
)
SIGNAL_NOT_BEFORE_VALIDATION_ENFORCED = (
    "NOT_BEFORE_VALIDATION_ENFORCED_OBSERVED"
)
SIGNAL_NOT_BEFORE_VALIDATION_ABSENT = (
    "NOT_BEFORE_VALIDATION_ABSENT_OBSERVED"
)
SIGNAL_NOT_BEFORE_VALIDATION_NOT_PROVIDED = (
    "NOT_BEFORE_VALIDATION_NOT_PROVIDED"
)
SIGNAL_CLAIM_VALIDATION_ENFORCED = "CLAIM_VALIDATION_ENFORCED_OBSERVED"
SIGNAL_CLAIM_VALIDATION_ABSENT = "CLAIM_VALIDATION_ABSENT_OBSERVED"
SIGNAL_CLAIM_VALIDATION_NOT_PROVIDED = "CLAIM_VALIDATION_NOT_PROVIDED"
SIGNAL_KEY_MANAGEMENT_MANAGED = "KEY_MANAGEMENT_MANAGED_OBSERVED"
SIGNAL_KEY_MANAGEMENT_STATIC = "KEY_MANAGEMENT_STATIC_KEY_OBSERVED"
SIGNAL_KEY_MANAGEMENT_EMBEDDED = "KEY_MANAGEMENT_EMBEDDED_KEY_OBSERVED"
SIGNAL_KEY_MANAGEMENT_ABSENT = "KEY_MANAGEMENT_ABSENT_OBSERVED"
SIGNAL_KEY_ROTATION_CONFIGURED = "KEY_ROTATION_CONFIGURED_OBSERVED"
SIGNAL_KEY_ROTATION_ABSENT = "KEY_ROTATION_ABSENT_OBSERVED"
SIGNAL_TOKEN_LIFETIME_SHORT = "TOKEN_LIFETIME_SHORT_OBSERVED"
SIGNAL_TOKEN_LIFETIME_LONG = "TOKEN_LIFETIME_LONG_OBSERVED"
SIGNAL_TOKEN_LIFETIME_UNBOUNDED = "TOKEN_LIFETIME_UNBOUNDED_OBSERVED"
SIGNAL_REFRESH_TOKEN_PRESENT = "REFRESH_TOKEN_PRESENT"
SIGNAL_REFRESH_TOKEN_ABSENT = "REFRESH_TOKEN_ABSENT_OBSERVED"
SIGNAL_REFRESH_CONTROL_ENFORCED = "REFRESH_CONTROL_ENFORCED_OBSERVED"
SIGNAL_REFRESH_CONTROL_ABSENT = "REFRESH_CONTROL_ABSENT_OBSERVED"
SIGNAL_REFRESH_CONTROL_NOT_PROVIDED = "REFRESH_CONTROL_NOT_PROVIDED"
SIGNAL_REVOCATION_CONTROL_ENFORCED = (
    "REVOCATION_CONTROL_ENFORCED_OBSERVED"
)
SIGNAL_REVOCATION_CONTROL_ABSENT = "REVOCATION_CONTROL_ABSENT_OBSERVED"
SIGNAL_REVOCATION_CONTROL_NOT_PROVIDED = (
    "REVOCATION_CONTROL_NOT_PROVIDED"
)
SIGNAL_SESSION_SERVER_SIDE = "SESSION_SERVER_SIDE_OBSERVED"
SIGNAL_SESSION_CLIENT_SIDE = "SESSION_CLIENT_SIDE_OBSERVED"
SIGNAL_SESSION_STATELESS_TOKEN = "SESSION_STATELESS_TOKEN_OBSERVED"
SIGNAL_STORAGE_SERVER_SIDE = "STORAGE_SERVER_SIDE_OBSERVED"
SIGNAL_STORAGE_MEMORY_ONLY = "STORAGE_MEMORY_ONLY_OBSERVED"
SIGNAL_STORAGE_COOKIE = "STORAGE_COOKIE_OBSERVED"
SIGNAL_STORAGE_LOCAL = "STORAGE_LOCAL_STORAGE_OBSERVED"
SIGNAL_STORAGE_SESSION = "STORAGE_SESSION_STORAGE_OBSERVED"
SIGNAL_COOKIE_SECURE_PRESENT = "COOKIE_SECURE_PRESENT"
SIGNAL_COOKIE_HTTP_ONLY_PRESENT = "COOKIE_HTTP_ONLY_PRESENT"
SIGNAL_COOKIE_SAME_SITE_PRESENT = "COOKIE_SAME_SITE_PRESENT"
SIGNAL_COOKIE_SECURITY_ATTRIBUTES_MISSING = (
    "COOKIE_SECURITY_ATTRIBUTES_MISSING"
)
SIGNAL_TOKEN_EXPOSURE_URL = "TOKEN_EXPOSURE_URL_OBSERVED"
SIGNAL_TOKEN_EXPOSURE_LOG = "TOKEN_EXPOSURE_LOG_OBSERVED"
SIGNAL_TOKEN_EXPOSURE_RESPONSE_BODY = "TOKEN_EXPOSURE_RESPONSE_BODY_OBSERVED"
SIGNAL_TOKEN_EXPOSURE_CLIENT_STORAGE = (
    "TOKEN_EXPOSURE_CLIENT_STORAGE_OBSERVED"
)
SIGNAL_AUTHORIZATION_BOUNDARY_SERVER_SIDE = (
    "AUTHORIZATION_BOUNDARY_SERVER_SIDE_OBSERVED"
)
SIGNAL_AUTHORIZATION_BOUNDARY_CLIENT_SIDE = (
    "AUTHORIZATION_BOUNDARY_CLIENT_SIDE_ONLY_OBSERVED"
)
SIGNAL_AUTHENTICATION_FLOW_OBSERVED = "AUTHENTICATION_FLOW_OBSERVED"
SIGNAL_AUTHENTICATION_CONTROL_ENFORCED = (
    "AUTHENTICATION_CONTROL_ENFORCED_OBSERVED"
)
SIGNAL_AUTHENTICATION_CONTROL_ABSENT = (
    "AUTHENTICATION_CONTROL_ABSENT_OBSERVED"
)
SIGNAL_AUTHENTICATION_CONTROL_NOT_PROVIDED = (
    "AUTHENTICATION_CONTROL_NOT_PROVIDED"
)
SIGNAL_MISSING_AUTHENTICATION_CONTEXT = "MISSING_AUTHENTICATION_CONTEXT"
SIGNAL_CONTEXT_UNKNOWN = "CONTEXT_UNKNOWN"

JWT_AUTHENTICATION_SIGNALS: tuple[str, ...] = (
    SIGNAL_AUTH_MECHANISM_NONE_OBSERVED,
    SIGNAL_AUTH_MECHANISM_BEARER_TOKEN,
    SIGNAL_AUTH_MECHANISM_JWT_BEARER,
    SIGNAL_AUTH_MECHANISM_COOKIE_SESSION,
    SIGNAL_AUTH_MECHANISM_OAUTH2,
    SIGNAL_AUTH_MECHANISM_API_KEY,
    SIGNAL_AUTH_MECHANISM_BASIC,
    SIGNAL_AUTH_MECHANISM_MUTUAL_TLS,
    SIGNAL_TOKEN_MECHANISM_JWT,
    SIGNAL_TOKEN_MECHANISM_OPAQUE_ACCESS,
    SIGNAL_TOKEN_MECHANISM_REFRESH,
    SIGNAL_TOKEN_MECHANISM_SESSION_COOKIE,
    SIGNAL_TOKEN_MECHANISM_NONE_OBSERVED,
    SIGNAL_JWT_FORMAT_COMPACT_JWS,
    SIGNAL_JWT_FORMAT_COMPACT_JWE,
    SIGNAL_SIGNING_ALGORITHM_METADATA_PRESENT,
    SIGNAL_SIGNING_ALGORITHM_NONE_OBSERVED,
    SIGNAL_SIGNING_METHOD_SYMMETRIC,
    SIGNAL_SIGNING_METHOD_ASYMMETRIC,
    SIGNAL_SIGNATURE_VERIFICATION_ENFORCED,
    SIGNAL_SIGNATURE_VERIFICATION_ABSENT,
    SIGNAL_SIGNATURE_VERIFICATION_NOT_PROVIDED,
    SIGNAL_ALGORITHM_VALIDATION_ENFORCED,
    SIGNAL_ALGORITHM_VALIDATION_ABSENT,
    SIGNAL_ALGORITHM_VALIDATION_NOT_PROVIDED,
    SIGNAL_ISSUER_VALIDATION_ENFORCED,
    SIGNAL_ISSUER_VALIDATION_ABSENT,
    SIGNAL_ISSUER_VALIDATION_NOT_PROVIDED,
    SIGNAL_AUDIENCE_VALIDATION_ENFORCED,
    SIGNAL_AUDIENCE_VALIDATION_ABSENT,
    SIGNAL_AUDIENCE_VALIDATION_NOT_PROVIDED,
    SIGNAL_EXPIRATION_VALIDATION_ENFORCED,
    SIGNAL_EXPIRATION_VALIDATION_ABSENT,
    SIGNAL_EXPIRATION_VALIDATION_NOT_PROVIDED,
    SIGNAL_NOT_BEFORE_VALIDATION_ENFORCED,
    SIGNAL_NOT_BEFORE_VALIDATION_ABSENT,
    SIGNAL_NOT_BEFORE_VALIDATION_NOT_PROVIDED,
    SIGNAL_CLAIM_VALIDATION_ENFORCED,
    SIGNAL_CLAIM_VALIDATION_ABSENT,
    SIGNAL_CLAIM_VALIDATION_NOT_PROVIDED,
    SIGNAL_KEY_MANAGEMENT_MANAGED,
    SIGNAL_KEY_MANAGEMENT_STATIC,
    SIGNAL_KEY_MANAGEMENT_EMBEDDED,
    SIGNAL_KEY_MANAGEMENT_ABSENT,
    SIGNAL_KEY_ROTATION_CONFIGURED,
    SIGNAL_KEY_ROTATION_ABSENT,
    SIGNAL_TOKEN_LIFETIME_SHORT,
    SIGNAL_TOKEN_LIFETIME_LONG,
    SIGNAL_TOKEN_LIFETIME_UNBOUNDED,
    SIGNAL_REFRESH_TOKEN_PRESENT,
    SIGNAL_REFRESH_TOKEN_ABSENT,
    SIGNAL_REFRESH_CONTROL_ENFORCED,
    SIGNAL_REFRESH_CONTROL_ABSENT,
    SIGNAL_REFRESH_CONTROL_NOT_PROVIDED,
    SIGNAL_REVOCATION_CONTROL_ENFORCED,
    SIGNAL_REVOCATION_CONTROL_ABSENT,
    SIGNAL_REVOCATION_CONTROL_NOT_PROVIDED,
    SIGNAL_SESSION_SERVER_SIDE,
    SIGNAL_SESSION_CLIENT_SIDE,
    SIGNAL_SESSION_STATELESS_TOKEN,
    SIGNAL_STORAGE_SERVER_SIDE,
    SIGNAL_STORAGE_MEMORY_ONLY,
    SIGNAL_STORAGE_COOKIE,
    SIGNAL_STORAGE_LOCAL,
    SIGNAL_STORAGE_SESSION,
    SIGNAL_COOKIE_SECURE_PRESENT,
    SIGNAL_COOKIE_HTTP_ONLY_PRESENT,
    SIGNAL_COOKIE_SAME_SITE_PRESENT,
    SIGNAL_COOKIE_SECURITY_ATTRIBUTES_MISSING,
    SIGNAL_TOKEN_EXPOSURE_URL,
    SIGNAL_TOKEN_EXPOSURE_LOG,
    SIGNAL_TOKEN_EXPOSURE_RESPONSE_BODY,
    SIGNAL_TOKEN_EXPOSURE_CLIENT_STORAGE,
    SIGNAL_AUTHORIZATION_BOUNDARY_SERVER_SIDE,
    SIGNAL_AUTHORIZATION_BOUNDARY_CLIENT_SIDE,
    SIGNAL_AUTHENTICATION_FLOW_OBSERVED,
    SIGNAL_AUTHENTICATION_CONTROL_ENFORCED,
    SIGNAL_AUTHENTICATION_CONTROL_ABSENT,
    SIGNAL_AUTHENTICATION_CONTROL_NOT_PROVIDED,
    SIGNAL_MISSING_AUTHENTICATION_CONTEXT,
    SIGNAL_CONTEXT_UNKNOWN,
)

# ---------------------------------------------------------------------------
# Closed limitations
# ---------------------------------------------------------------------------

LIMITATION_NO_EXPLOIT_CLAIM = "NO_EXPLOIT_CLAIM"
LIMITATION_NO_VULNERABILITY_CONFIRMATION = "NO_VULNERABILITY_CONFIRMATION"
LIMITATION_NO_SIGNATURE_BYPASS_CLAIM = "NO_SIGNATURE_BYPASS_CLAIM"
LIMITATION_NO_AUTHENTICATION_BYPASS_CLAIM = (
    "NO_AUTHENTICATION_BYPASS_CLAIM"
)
LIMITATION_HYPOTHESIS_ONLY = "HYPOTHESIS_ONLY"
LIMITATION_EVIDENCE_REQUIRED = "EVIDENCE_REQUIRED"
LIMITATION_INSUFFICIENT_CONTEXT = "INSUFFICIENT_CONTEXT"

JWT_AUTHENTICATION_HYPOTHESIS_LIMITATIONS: tuple[str, ...] = (
    LIMITATION_NO_EXPLOIT_CLAIM,
    LIMITATION_NO_VULNERABILITY_CONFIRMATION,
    LIMITATION_NO_SIGNATURE_BYPASS_CLAIM,
    LIMITATION_NO_AUTHENTICATION_BYPASS_CLAIM,
    LIMITATION_HYPOTHESIS_ONLY,
    LIMITATION_EVIDENCE_REQUIRED,
    LIMITATION_INSUFFICIENT_CONTEXT,
)

MAX_SIGNALS = 12
MAX_LIMITATIONS = 7
MAX_VALUE_LEN = 160
MAX_RATIONALE_LEN = 240

_CONTROL_RE = re.compile(r"[\x00-\x1f\x7f]+")


def _safe_text(value: object, limit: int = MAX_VALUE_LEN) -> str:
    text = _CONTROL_RE.sub(" ", str(value if value is not None else ""))
    return " ".join(text.split())[:limit]


def _require_codes(value: object, allowed: tuple, limit: int) -> list[str]:
    out: list[str] = []
    for item in value or ():
        text = _safe_text(item)
        if not text:
            continue
        if text not in allowed:
            raise ValueError(f"invalid closed code: {text!r}")
        if text not in out:
            out.append(text)
        if len(out) >= limit:
            break
    return out


def sanitize_jwt_authentication_hypothesis_plan(value: object) -> dict:
    """Project an R47.3 hypothesis onto its fixed bounded key set."""

    if not isinstance(value, dict):
        return {
            "rule_version": "",
            "hypothesis_type": TYPE_UNKNOWN,
            "hypothesis_state": STATE_UNKNOWN,
            "supporting_signals": [],
            "confidence": "UNKNOWN",
            "priority": "UNKNOWN",
            "rationale": "",
            "limitations": [],
            "research_only": True,
        }
    hypothesis_type = _safe_text(
        value.get("hypothesis_type")
    ).strip().upper()
    if hypothesis_type not in HYPOTHESIS_TYPES:
        hypothesis_type = TYPE_UNKNOWN
    hypothesis_state = _safe_text(
        value.get("hypothesis_state")
    ).strip().upper()
    if hypothesis_state not in HYPOTHESIS_STATES:
        hypothesis_state = STATE_UNKNOWN
    confidence = _safe_text(value.get("confidence")).strip().upper()
    if confidence not in CONFIDENCE_LEVELS:
        confidence = "UNKNOWN"
    priority = _safe_text(value.get("priority")).strip().upper()
    if priority not in CONFIDENCE_LEVELS:
        priority = "UNKNOWN"
    return {
        "rule_version": _safe_text(value.get("rule_version")),
        "hypothesis_type": hypothesis_type,
        "hypothesis_state": hypothesis_state,
        "supporting_signals": [
            signal
            for signal in (
                _safe_text(item)
                for item in value.get("supporting_signals") or ()
            )
            if signal in JWT_AUTHENTICATION_SIGNALS
        ][:MAX_SIGNALS],
        "confidence": confidence,
        "priority": priority,
        "rationale": _safe_text(
            value.get("rationale"), MAX_RATIONALE_LEN
        ),
        "limitations": [
            code
            for code in (
                _safe_text(item) for item in value.get("limitations") or ()
            )
            if code in JWT_AUTHENTICATION_HYPOTHESIS_LIMITATIONS
        ][:MAX_LIMITATIONS],
        "research_only": True,
    }


# ---------------------------------------------------------------------------
# Model
# ---------------------------------------------------------------------------


class JWTAuthenticationHypothesisPlan(BaseModel):
    """Deterministic research-only JWT/authentication hypothesis (R47.3)."""

    model_config = ConfigDict(extra="forbid")

    rule_version: str = JWT_AUTHENTICATION_HYPOTHESIS_RULE_VERSION
    hypothesis_type: str
    hypothesis_state: str = STATE_UNKNOWN
    supporting_signals: list[str] = Field(default_factory=list)
    confidence: str = "UNKNOWN"
    priority: str = "UNKNOWN"
    rationale: str = ""
    limitations: list[str] = Field(default_factory=list)
    research_only: bool = True

    @field_validator("rule_version")
    @classmethod
    def _fixed_rule(cls, value: object) -> str:
        return JWT_AUTHENTICATION_HYPOTHESIS_RULE_VERSION

    @field_validator("hypothesis_type")
    @classmethod
    def _valid_type(cls, value: object) -> str:
        text = _safe_text(value).strip().upper()
        if text not in HYPOTHESIS_TYPES:
            raise ValueError(f"invalid hypothesis_type: {value!r}")
        return text

    @field_validator("hypothesis_state")
    @classmethod
    def _valid_state(cls, value: object) -> str:
        text = _safe_text(value).strip().upper()
        if text not in HYPOTHESIS_STATES:
            raise ValueError(f"invalid hypothesis_state: {value!r}")
        return text

    @field_validator("supporting_signals")
    @classmethod
    def _valid_signals(cls, value: list) -> list[str]:
        return _require_codes(
            value, JWT_AUTHENTICATION_SIGNALS, MAX_SIGNALS
        )

    @field_validator("confidence", "priority")
    @classmethod
    def _valid_confidence(cls, value: object) -> str:
        text = _safe_text(value).strip().upper()
        if text not in CONFIDENCE_LEVELS:
            raise ValueError(f"invalid confidence/priority: {value!r}")
        return text

    @field_validator("rationale")
    @classmethod
    def _bounded_rationale(cls, value: object) -> str:
        return _safe_text(value, MAX_RATIONALE_LEN)

    @field_validator("limitations")
    @classmethod
    def _valid_limitations(cls, value: list) -> list[str]:
        return _require_codes(
            value, JWT_AUTHENTICATION_HYPOTHESIS_LIMITATIONS, MAX_LIMITATIONS
        )

    @field_validator("research_only")
    @classmethod
    def _research_only(cls, value: object) -> bool:
        if not value:
            raise ValueError(
                "jwt/authentication hypotheses are research-only"
            )
        return True


def jwt_authentication_hypothesis_plan_projection(
    value: JWTAuthenticationHypothesisPlan,
) -> dict:
    """Serialize an R47.3 hypothesis to a deterministic dict."""

    return value.model_dump(mode="json")


__all__ = [
    "JWT_AUTHENTICATION_HYPOTHESIS_RULE_VERSION",
    "RULE_VERSION",
    "TYPE_JWT_VALIDATION_GAP",
    "TYPE_SIGNATURE_VERIFICATION_GAP",
    "TYPE_ALGORITHM_VALIDATION_GAP",
    "TYPE_CLAIM_VALIDATION_GAP",
    "TYPE_ISSUER_VALIDATION_GAP",
    "TYPE_AUDIENCE_VALIDATION_GAP",
    "TYPE_EXPIRATION_VALIDATION_GAP",
    "TYPE_NOT_BEFORE_VALIDATION_GAP",
    "TYPE_KEY_MANAGEMENT_GAP",
    "TYPE_TOKEN_LIFETIME_RISK",
    "TYPE_TOKEN_STORAGE_RISK",
    "TYPE_TOKEN_REVOCATION_GAP",
    "TYPE_REFRESH_TOKEN_CONTROL_GAP",
    "TYPE_SESSION_MANAGEMENT_GAP",
    "TYPE_AUTHENTICATION_FLOW_GAP",
    "TYPE_AUTHENTICATION_CONTROL_PRESENT",
    "TYPE_MISSING_AUTHENTICATION_CONTEXT",
    "TYPE_UNKNOWN",
    "HYPOTHESIS_TYPES",
    "VALIDATION_GAP_HYPOTHESIS_TYPES",
    "CONTROL_GAP_HYPOTHESIS_TYPES",
    "STATE_WEAKNESS_OBSERVED",
    "STATE_CONTROL_PRESENT_OBSERVED",
    "STATE_NEEDS_EVIDENCE",
    "STATE_NOT_OBSERVED",
    "STATE_UNKNOWN",
    "HYPOTHESIS_STATES",
    "SIGNAL_AUTH_MECHANISM_NONE_OBSERVED",
    "SIGNAL_AUTH_MECHANISM_BEARER_TOKEN",
    "SIGNAL_AUTH_MECHANISM_JWT_BEARER",
    "SIGNAL_AUTH_MECHANISM_COOKIE_SESSION",
    "SIGNAL_AUTH_MECHANISM_OAUTH2",
    "SIGNAL_AUTH_MECHANISM_API_KEY",
    "SIGNAL_AUTH_MECHANISM_BASIC",
    "SIGNAL_AUTH_MECHANISM_MUTUAL_TLS",
    "SIGNAL_TOKEN_MECHANISM_JWT",
    "SIGNAL_TOKEN_MECHANISM_OPAQUE_ACCESS",
    "SIGNAL_TOKEN_MECHANISM_REFRESH",
    "SIGNAL_TOKEN_MECHANISM_SESSION_COOKIE",
    "SIGNAL_TOKEN_MECHANISM_NONE_OBSERVED",
    "SIGNAL_JWT_FORMAT_COMPACT_JWS",
    "SIGNAL_JWT_FORMAT_COMPACT_JWE",
    "SIGNAL_SIGNING_ALGORITHM_METADATA_PRESENT",
    "SIGNAL_SIGNING_ALGORITHM_NONE_OBSERVED",
    "SIGNAL_SIGNING_METHOD_SYMMETRIC",
    "SIGNAL_SIGNING_METHOD_ASYMMETRIC",
    "SIGNAL_SIGNATURE_VERIFICATION_ENFORCED",
    "SIGNAL_SIGNATURE_VERIFICATION_ABSENT",
    "SIGNAL_SIGNATURE_VERIFICATION_NOT_PROVIDED",
    "SIGNAL_ALGORITHM_VALIDATION_ENFORCED",
    "SIGNAL_ALGORITHM_VALIDATION_ABSENT",
    "SIGNAL_ALGORITHM_VALIDATION_NOT_PROVIDED",
    "SIGNAL_ISSUER_VALIDATION_ENFORCED",
    "SIGNAL_ISSUER_VALIDATION_ABSENT",
    "SIGNAL_ISSUER_VALIDATION_NOT_PROVIDED",
    "SIGNAL_AUDIENCE_VALIDATION_ENFORCED",
    "SIGNAL_AUDIENCE_VALIDATION_ABSENT",
    "SIGNAL_AUDIENCE_VALIDATION_NOT_PROVIDED",
    "SIGNAL_EXPIRATION_VALIDATION_ENFORCED",
    "SIGNAL_EXPIRATION_VALIDATION_ABSENT",
    "SIGNAL_EXPIRATION_VALIDATION_NOT_PROVIDED",
    "SIGNAL_NOT_BEFORE_VALIDATION_ENFORCED",
    "SIGNAL_NOT_BEFORE_VALIDATION_ABSENT",
    "SIGNAL_NOT_BEFORE_VALIDATION_NOT_PROVIDED",
    "SIGNAL_CLAIM_VALIDATION_ENFORCED",
    "SIGNAL_CLAIM_VALIDATION_ABSENT",
    "SIGNAL_CLAIM_VALIDATION_NOT_PROVIDED",
    "SIGNAL_KEY_MANAGEMENT_MANAGED",
    "SIGNAL_KEY_MANAGEMENT_STATIC",
    "SIGNAL_KEY_MANAGEMENT_EMBEDDED",
    "SIGNAL_KEY_MANAGEMENT_ABSENT",
    "SIGNAL_KEY_ROTATION_CONFIGURED",
    "SIGNAL_KEY_ROTATION_ABSENT",
    "SIGNAL_TOKEN_LIFETIME_SHORT",
    "SIGNAL_TOKEN_LIFETIME_LONG",
    "SIGNAL_TOKEN_LIFETIME_UNBOUNDED",
    "SIGNAL_REFRESH_TOKEN_PRESENT",
    "SIGNAL_REFRESH_TOKEN_ABSENT",
    "SIGNAL_REFRESH_CONTROL_ENFORCED",
    "SIGNAL_REFRESH_CONTROL_ABSENT",
    "SIGNAL_REFRESH_CONTROL_NOT_PROVIDED",
    "SIGNAL_REVOCATION_CONTROL_ENFORCED",
    "SIGNAL_REVOCATION_CONTROL_ABSENT",
    "SIGNAL_REVOCATION_CONTROL_NOT_PROVIDED",
    "SIGNAL_SESSION_SERVER_SIDE",
    "SIGNAL_SESSION_CLIENT_SIDE",
    "SIGNAL_SESSION_STATELESS_TOKEN",
    "SIGNAL_STORAGE_SERVER_SIDE",
    "SIGNAL_STORAGE_MEMORY_ONLY",
    "SIGNAL_STORAGE_COOKIE",
    "SIGNAL_STORAGE_LOCAL",
    "SIGNAL_STORAGE_SESSION",
    "SIGNAL_COOKIE_SECURE_PRESENT",
    "SIGNAL_COOKIE_HTTP_ONLY_PRESENT",
    "SIGNAL_COOKIE_SAME_SITE_PRESENT",
    "SIGNAL_COOKIE_SECURITY_ATTRIBUTES_MISSING",
    "SIGNAL_TOKEN_EXPOSURE_URL",
    "SIGNAL_TOKEN_EXPOSURE_LOG",
    "SIGNAL_TOKEN_EXPOSURE_RESPONSE_BODY",
    "SIGNAL_TOKEN_EXPOSURE_CLIENT_STORAGE",
    "SIGNAL_AUTHORIZATION_BOUNDARY_SERVER_SIDE",
    "SIGNAL_AUTHORIZATION_BOUNDARY_CLIENT_SIDE",
    "SIGNAL_AUTHENTICATION_FLOW_OBSERVED",
    "SIGNAL_AUTHENTICATION_CONTROL_ENFORCED",
    "SIGNAL_AUTHENTICATION_CONTROL_ABSENT",
    "SIGNAL_AUTHENTICATION_CONTROL_NOT_PROVIDED",
    "SIGNAL_MISSING_AUTHENTICATION_CONTEXT",
    "SIGNAL_CONTEXT_UNKNOWN",
    "JWT_AUTHENTICATION_SIGNALS",
    "LIMITATION_NO_EXPLOIT_CLAIM",
    "LIMITATION_NO_VULNERABILITY_CONFIRMATION",
    "LIMITATION_NO_SIGNATURE_BYPASS_CLAIM",
    "LIMITATION_NO_AUTHENTICATION_BYPASS_CLAIM",
    "LIMITATION_HYPOTHESIS_ONLY",
    "LIMITATION_EVIDENCE_REQUIRED",
    "LIMITATION_INSUFFICIENT_CONTEXT",
    "JWT_AUTHENTICATION_HYPOTHESIS_LIMITATIONS",
    "MAX_SIGNALS",
    "MAX_LIMITATIONS",
    "MAX_VALUE_LEN",
    "MAX_RATIONALE_LEN",
    "sanitize_jwt_authentication_hypothesis_plan",
    "JWTAuthenticationHypothesisPlan",
    "jwt_authentication_hypothesis_plan_projection",
]
