"""OAuth hypothesis schema (Stage R48.3).

An :class:`OAuthHypothesisPlan` is a deterministic research hypothesis
about possible OAuth protocol/authorization-flow control behavior. It
answers the research question:

    "Which OAuth research hypothesis follows from the supplied context?"

Hard boundaries encoded here:

- Research hypothesis only: no exploit claim, no vulnerability
  confirmation, no OAuth bypass, no redirect_uri exploitation, no CSRF
  exploitation, no token exchange, no token replay, no credential
  testing, no payload, no attack sequence, no execution.
- Technology presence is never a hypothesis of weakness by itself.
- Closed vocabularies: hypothesis type, hypothesis state, supporting
  signals, confidence, priority, rationale and limitations are
  closed/bounded.
- Confidence and priority reuse the shared evidence-confidence
  vocabulary. Priority means "how useful is further research of this
  OAuth hypothesis?"; it is NOT severity, exploitability, CVSS or
  vulnerability probability.
- ``hypothesis_state`` explicitly distinguishes an observed control, an
  observed weakness, a not-observed signal and a need for evidence.
- Bounded, privacy-safe, JSON serializable.

No I/O, no network, no LLM, no Mongo, no execution of any kind is
represented here.
"""

from __future__ import annotations

import re

from pydantic import BaseModel, ConfigDict, Field, field_validator

from ai.schemas.evidence_confidence import CONFIDENCE_LEVELS

OAUTH_HYPOTHESIS_RULE_VERSION = "r48-3"
RULE_VERSION = OAUTH_HYPOTHESIS_RULE_VERSION

# ---------------------------------------------------------------------------
# Closed hypothesis vocabulary
# ---------------------------------------------------------------------------

TYPE_REDIRECT_URI_VALIDATION_GAP = "REDIRECT_URI_VALIDATION_GAP"
TYPE_STATE_VALIDATION_GAP = "STATE_VALIDATION_GAP"
TYPE_NONCE_VALIDATION_GAP = "NONCE_VALIDATION_GAP"
TYPE_PKCE_ENFORCEMENT_GAP = "PKCE_ENFORCEMENT_GAP"
TYPE_PKCE_VERIFIER_VALIDATION_GAP = "PKCE_VERIFIER_VALIDATION_GAP"
TYPE_AUTHORIZATION_CODE_VALIDATION_GAP = "AUTHORIZATION_CODE_VALIDATION_GAP"
TYPE_AUTHORIZATION_CODE_REUSE_GAP = "AUTHORIZATION_CODE_REUSE_GAP"
TYPE_AUTHORIZATION_CODE_LIFETIME_RISK = "AUTHORIZATION_CODE_LIFETIME_RISK"
TYPE_CLIENT_AUTHENTICATION_GAP = "CLIENT_AUTHENTICATION_GAP"
TYPE_CLIENT_CONFIGURATION_GAP = "CLIENT_CONFIGURATION_GAP"
TYPE_SCOPE_VALIDATION_GAP = "SCOPE_VALIDATION_GAP"
TYPE_RESOURCE_AUDIENCE_VALIDATION_GAP = "RESOURCE_AUDIENCE_VALIDATION_GAP"
TYPE_ISSUER_VALIDATION_GAP = "ISSUER_VALIDATION_GAP"
TYPE_TOKEN_VALIDATION_GAP = "TOKEN_VALIDATION_GAP"
TYPE_REFRESH_TOKEN_ROTATION_GAP = "REFRESH_TOKEN_ROTATION_GAP"
TYPE_REFRESH_TOKEN_REVOCATION_GAP = "REFRESH_TOKEN_REVOCATION_GAP"
TYPE_CONSENT_CONTROL_GAP = "CONSENT_CONTROL_GAP"
TYPE_CSRF_PROTECTION_GAP = "CSRF_PROTECTION_GAP"
TYPE_LOGIN_CSRF_GAP = "LOGIN_CSRF_GAP"
TYPE_REDIRECT_HANDLING_RISK = "REDIRECT_HANDLING_RISK"
TYPE_IMPLICIT_FLOW_RISK = "IMPLICIT_FLOW_RISK"
TYPE_TOKEN_EXPOSURE_RISK = "TOKEN_EXPOSURE_RISK"
TYPE_AUTHORIZATION_FLOW_GAP = "AUTHORIZATION_FLOW_GAP"
TYPE_AUTHENTICATION_CONTROL_PRESENT = "AUTHENTICATION_CONTROL_PRESENT"
TYPE_MISSING_OAUTH_CONTEXT = "MISSING_OAUTH_CONTEXT"
TYPE_UNKNOWN = "UNKNOWN"

HYPOTHESIS_TYPES: tuple[str, ...] = (
    TYPE_REDIRECT_URI_VALIDATION_GAP,
    TYPE_STATE_VALIDATION_GAP,
    TYPE_NONCE_VALIDATION_GAP,
    TYPE_PKCE_ENFORCEMENT_GAP,
    TYPE_PKCE_VERIFIER_VALIDATION_GAP,
    TYPE_AUTHORIZATION_CODE_VALIDATION_GAP,
    TYPE_AUTHORIZATION_CODE_REUSE_GAP,
    TYPE_AUTHORIZATION_CODE_LIFETIME_RISK,
    TYPE_CLIENT_AUTHENTICATION_GAP,
    TYPE_CLIENT_CONFIGURATION_GAP,
    TYPE_SCOPE_VALIDATION_GAP,
    TYPE_RESOURCE_AUDIENCE_VALIDATION_GAP,
    TYPE_ISSUER_VALIDATION_GAP,
    TYPE_TOKEN_VALIDATION_GAP,
    TYPE_REFRESH_TOKEN_ROTATION_GAP,
    TYPE_REFRESH_TOKEN_REVOCATION_GAP,
    TYPE_CONSENT_CONTROL_GAP,
    TYPE_CSRF_PROTECTION_GAP,
    TYPE_LOGIN_CSRF_GAP,
    TYPE_REDIRECT_HANDLING_RISK,
    TYPE_IMPLICIT_FLOW_RISK,
    TYPE_TOKEN_EXPOSURE_RISK,
    TYPE_AUTHORIZATION_FLOW_GAP,
    TYPE_AUTHENTICATION_CONTROL_PRESENT,
    TYPE_MISSING_OAUTH_CONTEXT,
    TYPE_UNKNOWN,
)

VALIDATION_GAP_HYPOTHESIS_TYPES: tuple[str, ...] = (
    TYPE_REDIRECT_URI_VALIDATION_GAP,
    TYPE_STATE_VALIDATION_GAP,
    TYPE_NONCE_VALIDATION_GAP,
    TYPE_PKCE_ENFORCEMENT_GAP,
    TYPE_PKCE_VERIFIER_VALIDATION_GAP,
    TYPE_AUTHORIZATION_CODE_VALIDATION_GAP,
    TYPE_AUTHORIZATION_CODE_REUSE_GAP,
    TYPE_CLIENT_AUTHENTICATION_GAP,
    TYPE_SCOPE_VALIDATION_GAP,
    TYPE_RESOURCE_AUDIENCE_VALIDATION_GAP,
    TYPE_ISSUER_VALIDATION_GAP,
    TYPE_TOKEN_VALIDATION_GAP,
    TYPE_REFRESH_TOKEN_ROTATION_GAP,
    TYPE_REFRESH_TOKEN_REVOCATION_GAP,
    TYPE_CSRF_PROTECTION_GAP,
    TYPE_LOGIN_CSRF_GAP,
)

RISK_HYPOTHESIS_TYPES: tuple[str, ...] = (
    TYPE_AUTHORIZATION_CODE_LIFETIME_RISK,
    TYPE_CLIENT_CONFIGURATION_GAP,
    TYPE_CONSENT_CONTROL_GAP,
    TYPE_REDIRECT_HANDLING_RISK,
    TYPE_IMPLICIT_FLOW_RISK,
    TYPE_TOKEN_EXPOSURE_RISK,
    TYPE_AUTHORIZATION_FLOW_GAP,
)

# ---------------------------------------------------------------------------
# Closed hypothesis states
# ---------------------------------------------------------------------------

STATE_WEAKNESS_OBSERVED = "WEAKNESS_OBSERVED"
STATE_CONTROL_PRESENT_OBSERVED = "CONTROL_PRESENT_OBSERVED"
STATE_NEEDS_EVIDENCE = "NEEDS_EVIDENCE"
STATE_NOT_OBSERVED = "NOT_OBSERVED"
STATE_UNKNOWN = "UNKNOWN"

HYPOTHESIS_STATES: tuple[str, ...] = (
    STATE_WEAKNESS_OBSERVED,
    STATE_CONTROL_PRESENT_OBSERVED,
    STATE_NEEDS_EVIDENCE,
    STATE_NOT_OBSERVED,
    STATE_UNKNOWN,
)

# ---------------------------------------------------------------------------
# Closed supporting-signal vocabulary
# ---------------------------------------------------------------------------

SIGNAL_OAUTH2_OBSERVED = "OAUTH2_OBSERVED"
SIGNAL_OAUTH2_1_OBSERVED = "OAUTH2_1_OBSERVED"
SIGNAL_FLOW_AUTHORIZATION_CODE = "FLOW_AUTHORIZATION_CODE_OBSERVED"
SIGNAL_FLOW_AUTHORIZATION_CODE_PKCE = "FLOW_AUTHORIZATION_CODE_PKCE_OBSERVED"
SIGNAL_FLOW_IMPLICIT = "FLOW_IMPLICIT_OBSERVED"
SIGNAL_FLOW_CLIENT_CREDENTIALS = "FLOW_CLIENT_CREDENTIALS_OBSERVED"
SIGNAL_FLOW_DEVICE_AUTHORIZATION = "FLOW_DEVICE_AUTHORIZATION_OBSERVED"
SIGNAL_FLOW_REFRESH_TOKEN = "FLOW_REFRESH_TOKEN_OBSERVED"
SIGNAL_FLOW_HYBRID = "FLOW_HYBRID_OBSERVED"
SIGNAL_CLIENT_TYPE_PUBLIC = "CLIENT_TYPE_PUBLIC_OBSERVED"
SIGNAL_CLIENT_TYPE_CONFIDENTIAL = "CLIENT_TYPE_CONFIDENTIAL_OBSERVED"
SIGNAL_AUTHORIZATION_SERVER_OBSERVED = "AUTHORIZATION_SERVER_OBSERVED"
SIGNAL_RESOURCE_SERVER_OBSERVED = "RESOURCE_SERVER_OBSERVED"
SIGNAL_AUTHORIZATION_ENDPOINT_OBSERVED = "AUTHORIZATION_ENDPOINT_OBSERVED"
SIGNAL_TOKEN_ENDPOINT_OBSERVED = "TOKEN_ENDPOINT_OBSERVED"
SIGNAL_REDIRECT_URI_PARAM_OBSERVED = "REDIRECT_URI_PARAM_OBSERVED"
SIGNAL_CLIENT_ID_OBSERVED = "CLIENT_ID_OBSERVED"
SIGNAL_RESPONSE_TYPE_CODE = "RESPONSE_TYPE_CODE_OBSERVED"
SIGNAL_RESPONSE_TYPE_TOKEN = "RESPONSE_TYPE_TOKEN_OBSERVED"
SIGNAL_RESPONSE_TYPE_ID_TOKEN = "RESPONSE_TYPE_ID_TOKEN_OBSERVED"
SIGNAL_GRANT_TYPE_AUTHORIZATION_CODE = "GRANT_TYPE_AUTHORIZATION_CODE_OBSERVED"
SIGNAL_GRANT_TYPE_REFRESH_TOKEN = "GRANT_TYPE_REFRESH_TOKEN_OBSERVED"
SIGNAL_GRANT_TYPE_CLIENT_CREDENTIALS = (
    "GRANT_TYPE_CLIENT_CREDENTIALS_OBSERVED"
)
SIGNAL_SCOPE_OBSERVED = "SCOPE_OBSERVED"
SIGNAL_STATE_PARAM_OBSERVED = "STATE_PARAM_OBSERVED"
SIGNAL_NONCE_PARAM_OBSERVED = "NONCE_PARAM_OBSERVED"
SIGNAL_PKCE_CHALLENGE_OBSERVED = "PKCE_CHALLENGE_OBSERVED"
SIGNAL_REDIRECT_URI_VALIDATION_ENFORCED = (
    "REDIRECT_URI_VALIDATION_ENFORCED_OBSERVED"
)
SIGNAL_REDIRECT_URI_VALIDATION_ABSENT = (
    "REDIRECT_URI_VALIDATION_ABSENT_OBSERVED"
)
SIGNAL_REDIRECT_URI_VALIDATION_NOT_PROVIDED = (
    "REDIRECT_URI_VALIDATION_NOT_PROVIDED"
)
SIGNAL_EXACT_REDIRECT_MATCHING_ENFORCED = (
    "EXACT_REDIRECT_MATCHING_ENFORCED_OBSERVED"
)
SIGNAL_EXACT_REDIRECT_MATCHING_ABSENT = (
    "EXACT_REDIRECT_MATCHING_ABSENT_OBSERVED"
)
SIGNAL_EXACT_REDIRECT_MATCHING_NOT_PROVIDED = (
    "EXACT_REDIRECT_MATCHING_NOT_PROVIDED"
)
SIGNAL_STATE_VALIDATION_ENFORCED = "STATE_VALIDATION_ENFORCED_OBSERVED"
SIGNAL_STATE_VALIDATION_ABSENT = "STATE_VALIDATION_ABSENT_OBSERVED"
SIGNAL_STATE_VALIDATION_NOT_PROVIDED = "STATE_VALIDATION_NOT_PROVIDED"
SIGNAL_STATE_BINDING_ENFORCED = "STATE_BINDING_ENFORCED_OBSERVED"
SIGNAL_STATE_BINDING_ABSENT = "STATE_BINDING_ABSENT_OBSERVED"
SIGNAL_STATE_BINDING_NOT_PROVIDED = "STATE_BINDING_NOT_PROVIDED"
SIGNAL_NONCE_VALIDATION_ENFORCED = "NONCE_VALIDATION_ENFORCED_OBSERVED"
SIGNAL_NONCE_VALIDATION_ABSENT = "NONCE_VALIDATION_ABSENT_OBSERVED"
SIGNAL_NONCE_VALIDATION_NOT_PROVIDED = "NONCE_VALIDATION_NOT_PROVIDED"
SIGNAL_PKCE_ENFORCEMENT_ENFORCED = "PKCE_ENFORCEMENT_ENFORCED_OBSERVED"
SIGNAL_PKCE_ENFORCEMENT_ABSENT = "PKCE_ENFORCEMENT_ABSENT_OBSERVED"
SIGNAL_PKCE_ENFORCEMENT_NOT_PROVIDED = "PKCE_ENFORCEMENT_NOT_PROVIDED"
SIGNAL_PKCE_VERIFIER_VALIDATION_ENFORCED = (
    "PKCE_VERIFIER_VALIDATION_ENFORCED_OBSERVED"
)
SIGNAL_PKCE_VERIFIER_VALIDATION_ABSENT = (
    "PKCE_VERIFIER_VALIDATION_ABSENT_OBSERVED"
)
SIGNAL_PKCE_VERIFIER_VALIDATION_NOT_PROVIDED = (
    "PKCE_VERIFIER_VALIDATION_NOT_PROVIDED"
)
SIGNAL_AUTHORIZATION_CODE_BINDING_ENFORCED = (
    "AUTHORIZATION_CODE_BINDING_ENFORCED_OBSERVED"
)
SIGNAL_AUTHORIZATION_CODE_BINDING_ABSENT = (
    "AUTHORIZATION_CODE_BINDING_ABSENT_OBSERVED"
)
SIGNAL_AUTHORIZATION_CODE_BINDING_NOT_PROVIDED = (
    "AUTHORIZATION_CODE_BINDING_NOT_PROVIDED"
)
SIGNAL_CODE_REUSE_CONTROL_ENFORCED = "CODE_REUSE_CONTROL_ENFORCED_OBSERVED"
SIGNAL_CODE_REUSE_CONTROL_ABSENT = "CODE_REUSE_CONTROL_ABSENT_OBSERVED"
SIGNAL_CODE_REUSE_CONTROL_NOT_PROVIDED = "CODE_REUSE_CONTROL_NOT_PROVIDED"
SIGNAL_CLIENT_AUTHENTICATION_ENFORCED = (
    "CLIENT_AUTHENTICATION_ENFORCED_OBSERVED"
)
SIGNAL_CLIENT_AUTHENTICATION_ABSENT = "CLIENT_AUTHENTICATION_ABSENT_OBSERVED"
SIGNAL_CLIENT_AUTHENTICATION_NOT_PROVIDED = (
    "CLIENT_AUTHENTICATION_NOT_PROVIDED"
)
SIGNAL_SCOPE_VALIDATION_ENFORCED = "SCOPE_VALIDATION_ENFORCED_OBSERVED"
SIGNAL_SCOPE_VALIDATION_ABSENT = "SCOPE_VALIDATION_ABSENT_OBSERVED"
SIGNAL_SCOPE_VALIDATION_NOT_PROVIDED = "SCOPE_VALIDATION_NOT_PROVIDED"
SIGNAL_RESOURCE_AUDIENCE_VALIDATION_ENFORCED = (
    "RESOURCE_AUDIENCE_VALIDATION_ENFORCED_OBSERVED"
)
SIGNAL_RESOURCE_AUDIENCE_VALIDATION_ABSENT = (
    "RESOURCE_AUDIENCE_VALIDATION_ABSENT_OBSERVED"
)
SIGNAL_RESOURCE_AUDIENCE_VALIDATION_NOT_PROVIDED = (
    "RESOURCE_AUDIENCE_VALIDATION_NOT_PROVIDED"
)
SIGNAL_ISSUER_VALIDATION_ENFORCED = "ISSUER_VALIDATION_ENFORCED_OBSERVED"
SIGNAL_ISSUER_VALIDATION_ABSENT = "ISSUER_VALIDATION_ABSENT_OBSERVED"
SIGNAL_ISSUER_VALIDATION_NOT_PROVIDED = "ISSUER_VALIDATION_NOT_PROVIDED"
SIGNAL_TOKEN_VALIDATION_ENFORCED = "TOKEN_VALIDATION_ENFORCED_OBSERVED"
SIGNAL_TOKEN_VALIDATION_ABSENT = "TOKEN_VALIDATION_ABSENT_OBSERVED"
SIGNAL_TOKEN_VALIDATION_NOT_PROVIDED = "TOKEN_VALIDATION_NOT_PROVIDED"
SIGNAL_REFRESH_TOKEN_ROTATION_ENFORCED = (
    "REFRESH_TOKEN_ROTATION_ENFORCED_OBSERVED"
)
SIGNAL_REFRESH_TOKEN_ROTATION_ABSENT = (
    "REFRESH_TOKEN_ROTATION_ABSENT_OBSERVED"
)
SIGNAL_REFRESH_TOKEN_ROTATION_NOT_PROVIDED = (
    "REFRESH_TOKEN_ROTATION_NOT_PROVIDED"
)
SIGNAL_REFRESH_TOKEN_REVOCATION_ENFORCED = (
    "REFRESH_TOKEN_REVOCATION_ENFORCED_OBSERVED"
)
SIGNAL_REFRESH_TOKEN_REVOCATION_ABSENT = (
    "REFRESH_TOKEN_REVOCATION_ABSENT_OBSERVED"
)
SIGNAL_REFRESH_TOKEN_REVOCATION_NOT_PROVIDED = (
    "REFRESH_TOKEN_REVOCATION_NOT_PROVIDED"
)
SIGNAL_CONSENT_CONTROL_ENFORCED = "CONSENT_CONTROL_ENFORCED_OBSERVED"
SIGNAL_CONSENT_CONTROL_ABSENT = "CONSENT_CONTROL_ABSENT_OBSERVED"
SIGNAL_CONSENT_CONTROL_NOT_PROVIDED = "CONSENT_CONTROL_NOT_PROVIDED"
SIGNAL_CSRF_PROTECTION_ENFORCED = "CSRF_PROTECTION_ENFORCED_OBSERVED"
SIGNAL_CSRF_PROTECTION_ABSENT = "CSRF_PROTECTION_ABSENT_OBSERVED"
SIGNAL_CSRF_PROTECTION_NOT_PROVIDED = "CSRF_PROTECTION_NOT_PROVIDED"
SIGNAL_LOGIN_CSRF_PROTECTION_ENFORCED = (
    "LOGIN_CSRF_PROTECTION_ENFORCED_OBSERVED"
)
SIGNAL_LOGIN_CSRF_PROTECTION_ABSENT = (
    "LOGIN_CSRF_PROTECTION_ABSENT_OBSERVED"
)
SIGNAL_LOGIN_CSRF_PROTECTION_NOT_PROVIDED = (
    "LOGIN_CSRF_PROTECTION_NOT_PROVIDED"
)
SIGNAL_REDIRECT_HANDLING_ENFORCED = "REDIRECT_HANDLING_ENFORCED_OBSERVED"
SIGNAL_REDIRECT_HANDLING_ABSENT = "REDIRECT_HANDLING_ABSENT_OBSERVED"
SIGNAL_REDIRECT_HANDLING_NOT_PROVIDED = "REDIRECT_HANDLING_NOT_PROVIDED"
SIGNAL_REDIRECT_REGISTRATION_EXACT = "REDIRECT_REGISTRATION_EXACT_OBSERVED"
SIGNAL_REDIRECT_REGISTRATION_WILDCARD = (
    "REDIRECT_REGISTRATION_WILDCARD_OBSERVED"
)
SIGNAL_CODE_LIFETIME_SHORT = "CODE_LIFETIME_SHORT_OBSERVED"
SIGNAL_CODE_LIFETIME_LONG = "CODE_LIFETIME_LONG_OBSERVED"
SIGNAL_CODE_LIFETIME_UNBOUNDED = "CODE_LIFETIME_UNBOUNDED_OBSERVED"
SIGNAL_TOKEN_AUTH_CLIENT_SECRET_BASIC = "TOKEN_AUTH_CLIENT_SECRET_BASIC"
SIGNAL_TOKEN_AUTH_CLIENT_SECRET_POST = "TOKEN_AUTH_CLIENT_SECRET_POST"
SIGNAL_TOKEN_AUTH_PRIVATE_KEY_JWT = "TOKEN_AUTH_PRIVATE_KEY_JWT"
SIGNAL_TOKEN_AUTH_TLS_CLIENT_AUTH = "TOKEN_AUTH_TLS_CLIENT_AUTH"
SIGNAL_TOKEN_AUTH_NONE_OBSERVED = "TOKEN_AUTH_NONE_OBSERVED"
SIGNAL_CLIENT_SECRET_REQUIRED = "CLIENT_SECRET_REQUIRED_OBSERVED"
SIGNAL_CLIENT_SECRET_NOT_REQUIRED = "CLIENT_SECRET_NOT_REQUIRED_OBSERVED"
SIGNAL_REFRESH_TOKEN_OBSERVED = "REFRESH_TOKEN_OBSERVED"
SIGNAL_TOKEN_EXPOSURE_URL = "TOKEN_EXPOSURE_URL_OBSERVED"
SIGNAL_TOKEN_EXPOSURE_BROWSER_STORAGE = (
    "TOKEN_EXPOSURE_BROWSER_STORAGE_OBSERVED"
)
SIGNAL_TOKEN_EXPOSURE_RESPONSE_BODY = (
    "TOKEN_EXPOSURE_RESPONSE_BODY_OBSERVED"
)
SIGNAL_TOKEN_EXPOSURE_LOG = "TOKEN_EXPOSURE_LOG_OBSERVED"
SIGNAL_TOKEN_EXPOSURE_REFERRER = "TOKEN_EXPOSURE_REFERRER_OBSERVED"
SIGNAL_TOKEN_EXPOSURE_CLIENT_STORAGE = (
    "TOKEN_EXPOSURE_CLIENT_STORAGE_OBSERVED"
)
SIGNAL_AUTHORIZATION_BOUNDARY_SERVER_SIDE = (
    "AUTHORIZATION_BOUNDARY_SERVER_SIDE_OBSERVED"
)
SIGNAL_AUTHORIZATION_BOUNDARY_CLIENT_SIDE = (
    "AUTHORIZATION_BOUNDARY_CLIENT_SIDE_ONLY_OBSERVED"
)
SIGNAL_SESSION_SERVER_SIDE = "SESSION_SERVER_SIDE_OBSERVED"
SIGNAL_SESSION_CLIENT_SIDE = "SESSION_CLIENT_SIDE_OBSERVED"
SIGNAL_SESSION_STATELESS_TOKEN = "SESSION_STATELESS_TOKEN_OBSERVED"
SIGNAL_MISSING_OAUTH_CONTEXT = "MISSING_OAUTH_CONTEXT"
SIGNAL_CONTEXT_UNKNOWN = "CONTEXT_UNKNOWN"

OAUTH_SIGNALS: tuple[str, ...] = (
    SIGNAL_OAUTH2_OBSERVED,
    SIGNAL_OAUTH2_1_OBSERVED,
    SIGNAL_FLOW_AUTHORIZATION_CODE,
    SIGNAL_FLOW_AUTHORIZATION_CODE_PKCE,
    SIGNAL_FLOW_IMPLICIT,
    SIGNAL_FLOW_CLIENT_CREDENTIALS,
    SIGNAL_FLOW_DEVICE_AUTHORIZATION,
    SIGNAL_FLOW_REFRESH_TOKEN,
    SIGNAL_FLOW_HYBRID,
    SIGNAL_CLIENT_TYPE_PUBLIC,
    SIGNAL_CLIENT_TYPE_CONFIDENTIAL,
    SIGNAL_AUTHORIZATION_SERVER_OBSERVED,
    SIGNAL_RESOURCE_SERVER_OBSERVED,
    SIGNAL_AUTHORIZATION_ENDPOINT_OBSERVED,
    SIGNAL_TOKEN_ENDPOINT_OBSERVED,
    SIGNAL_REDIRECT_URI_PARAM_OBSERVED,
    SIGNAL_CLIENT_ID_OBSERVED,
    SIGNAL_RESPONSE_TYPE_CODE,
    SIGNAL_RESPONSE_TYPE_TOKEN,
    SIGNAL_RESPONSE_TYPE_ID_TOKEN,
    SIGNAL_GRANT_TYPE_AUTHORIZATION_CODE,
    SIGNAL_GRANT_TYPE_REFRESH_TOKEN,
    SIGNAL_GRANT_TYPE_CLIENT_CREDENTIALS,
    SIGNAL_SCOPE_OBSERVED,
    SIGNAL_STATE_PARAM_OBSERVED,
    SIGNAL_NONCE_PARAM_OBSERVED,
    SIGNAL_PKCE_CHALLENGE_OBSERVED,
    SIGNAL_REDIRECT_URI_VALIDATION_ENFORCED,
    SIGNAL_REDIRECT_URI_VALIDATION_ABSENT,
    SIGNAL_REDIRECT_URI_VALIDATION_NOT_PROVIDED,
    SIGNAL_EXACT_REDIRECT_MATCHING_ENFORCED,
    SIGNAL_EXACT_REDIRECT_MATCHING_ABSENT,
    SIGNAL_EXACT_REDIRECT_MATCHING_NOT_PROVIDED,
    SIGNAL_STATE_VALIDATION_ENFORCED,
    SIGNAL_STATE_VALIDATION_ABSENT,
    SIGNAL_STATE_VALIDATION_NOT_PROVIDED,
    SIGNAL_STATE_BINDING_ENFORCED,
    SIGNAL_STATE_BINDING_ABSENT,
    SIGNAL_STATE_BINDING_NOT_PROVIDED,
    SIGNAL_NONCE_VALIDATION_ENFORCED,
    SIGNAL_NONCE_VALIDATION_ABSENT,
    SIGNAL_NONCE_VALIDATION_NOT_PROVIDED,
    SIGNAL_PKCE_ENFORCEMENT_ENFORCED,
    SIGNAL_PKCE_ENFORCEMENT_ABSENT,
    SIGNAL_PKCE_ENFORCEMENT_NOT_PROVIDED,
    SIGNAL_PKCE_VERIFIER_VALIDATION_ENFORCED,
    SIGNAL_PKCE_VERIFIER_VALIDATION_ABSENT,
    SIGNAL_PKCE_VERIFIER_VALIDATION_NOT_PROVIDED,
    SIGNAL_AUTHORIZATION_CODE_BINDING_ENFORCED,
    SIGNAL_AUTHORIZATION_CODE_BINDING_ABSENT,
    SIGNAL_AUTHORIZATION_CODE_BINDING_NOT_PROVIDED,
    SIGNAL_CODE_REUSE_CONTROL_ENFORCED,
    SIGNAL_CODE_REUSE_CONTROL_ABSENT,
    SIGNAL_CODE_REUSE_CONTROL_NOT_PROVIDED,
    SIGNAL_CLIENT_AUTHENTICATION_ENFORCED,
    SIGNAL_CLIENT_AUTHENTICATION_ABSENT,
    SIGNAL_CLIENT_AUTHENTICATION_NOT_PROVIDED,
    SIGNAL_SCOPE_VALIDATION_ENFORCED,
    SIGNAL_SCOPE_VALIDATION_ABSENT,
    SIGNAL_SCOPE_VALIDATION_NOT_PROVIDED,
    SIGNAL_RESOURCE_AUDIENCE_VALIDATION_ENFORCED,
    SIGNAL_RESOURCE_AUDIENCE_VALIDATION_ABSENT,
    SIGNAL_RESOURCE_AUDIENCE_VALIDATION_NOT_PROVIDED,
    SIGNAL_ISSUER_VALIDATION_ENFORCED,
    SIGNAL_ISSUER_VALIDATION_ABSENT,
    SIGNAL_ISSUER_VALIDATION_NOT_PROVIDED,
    SIGNAL_TOKEN_VALIDATION_ENFORCED,
    SIGNAL_TOKEN_VALIDATION_ABSENT,
    SIGNAL_TOKEN_VALIDATION_NOT_PROVIDED,
    SIGNAL_REFRESH_TOKEN_ROTATION_ENFORCED,
    SIGNAL_REFRESH_TOKEN_ROTATION_ABSENT,
    SIGNAL_REFRESH_TOKEN_ROTATION_NOT_PROVIDED,
    SIGNAL_REFRESH_TOKEN_REVOCATION_ENFORCED,
    SIGNAL_REFRESH_TOKEN_REVOCATION_ABSENT,
    SIGNAL_REFRESH_TOKEN_REVOCATION_NOT_PROVIDED,
    SIGNAL_CONSENT_CONTROL_ENFORCED,
    SIGNAL_CONSENT_CONTROL_ABSENT,
    SIGNAL_CONSENT_CONTROL_NOT_PROVIDED,
    SIGNAL_CSRF_PROTECTION_ENFORCED,
    SIGNAL_CSRF_PROTECTION_ABSENT,
    SIGNAL_CSRF_PROTECTION_NOT_PROVIDED,
    SIGNAL_LOGIN_CSRF_PROTECTION_ENFORCED,
    SIGNAL_LOGIN_CSRF_PROTECTION_ABSENT,
    SIGNAL_LOGIN_CSRF_PROTECTION_NOT_PROVIDED,
    SIGNAL_REDIRECT_HANDLING_ENFORCED,
    SIGNAL_REDIRECT_HANDLING_ABSENT,
    SIGNAL_REDIRECT_HANDLING_NOT_PROVIDED,
    SIGNAL_REDIRECT_REGISTRATION_EXACT,
    SIGNAL_REDIRECT_REGISTRATION_WILDCARD,
    SIGNAL_CODE_LIFETIME_SHORT,
    SIGNAL_CODE_LIFETIME_LONG,
    SIGNAL_CODE_LIFETIME_UNBOUNDED,
    SIGNAL_TOKEN_AUTH_CLIENT_SECRET_BASIC,
    SIGNAL_TOKEN_AUTH_CLIENT_SECRET_POST,
    SIGNAL_TOKEN_AUTH_PRIVATE_KEY_JWT,
    SIGNAL_TOKEN_AUTH_TLS_CLIENT_AUTH,
    SIGNAL_TOKEN_AUTH_NONE_OBSERVED,
    SIGNAL_CLIENT_SECRET_REQUIRED,
    SIGNAL_CLIENT_SECRET_NOT_REQUIRED,
    SIGNAL_REFRESH_TOKEN_OBSERVED,
    SIGNAL_TOKEN_EXPOSURE_URL,
    SIGNAL_TOKEN_EXPOSURE_BROWSER_STORAGE,
    SIGNAL_TOKEN_EXPOSURE_RESPONSE_BODY,
    SIGNAL_TOKEN_EXPOSURE_LOG,
    SIGNAL_TOKEN_EXPOSURE_REFERRER,
    SIGNAL_TOKEN_EXPOSURE_CLIENT_STORAGE,
    SIGNAL_AUTHORIZATION_BOUNDARY_SERVER_SIDE,
    SIGNAL_AUTHORIZATION_BOUNDARY_CLIENT_SIDE,
    SIGNAL_SESSION_SERVER_SIDE,
    SIGNAL_SESSION_CLIENT_SIDE,
    SIGNAL_SESSION_STATELESS_TOKEN,
    SIGNAL_MISSING_OAUTH_CONTEXT,
    SIGNAL_CONTEXT_UNKNOWN,
)

# ---------------------------------------------------------------------------
# Closed limitations
# ---------------------------------------------------------------------------

LIMITATION_NO_EXPLOIT_CLAIM = "NO_EXPLOIT_CLAIM"
LIMITATION_NO_VULNERABILITY_CONFIRMATION = "NO_VULNERABILITY_CONFIRMATION"
LIMITATION_NO_OAUTH_BYPASS_CLAIM = "NO_OAUTH_BYPASS_CLAIM"
LIMITATION_NO_REDIRECT_URI_EXPLOIT_CLAIM = "NO_REDIRECT_URI_EXPLOIT_CLAIM"
LIMITATION_NO_TOKEN_EXCHANGE_CLAIM = "NO_TOKEN_EXCHANGE_CLAIM"
LIMITATION_NO_CSRF_EXPLOIT_CLAIM = "NO_CSRF_EXPLOIT_CLAIM"
LIMITATION_HYPOTHESIS_ONLY = "HYPOTHESIS_ONLY"
LIMITATION_EVIDENCE_REQUIRED = "EVIDENCE_REQUIRED"
LIMITATION_INSUFFICIENT_CONTEXT = "INSUFFICIENT_CONTEXT"

OAUTH_HYPOTHESIS_LIMITATIONS: tuple[str, ...] = (
    LIMITATION_NO_EXPLOIT_CLAIM,
    LIMITATION_NO_VULNERABILITY_CONFIRMATION,
    LIMITATION_NO_OAUTH_BYPASS_CLAIM,
    LIMITATION_NO_REDIRECT_URI_EXPLOIT_CLAIM,
    LIMITATION_NO_TOKEN_EXCHANGE_CLAIM,
    LIMITATION_NO_CSRF_EXPLOIT_CLAIM,
    LIMITATION_HYPOTHESIS_ONLY,
    LIMITATION_EVIDENCE_REQUIRED,
    LIMITATION_INSUFFICIENT_CONTEXT,
)

MAX_SIGNALS = 12
MAX_LIMITATIONS = 9
MAX_VALUE_LEN = 160
MAX_RATIONALE_LEN = 240

_CONTROL_RE = re.compile(r"[\x00-\x1f\x7f]+")


def _safe_text(value: object, limit: int = MAX_VALUE_LEN) -> str:
    text = _CONTROL_RE.sub(" ", str(value if value is not None else ""))
    return " ".join(text.split())[:limit]


def _require_codes(value: object, allowed: tuple, limit: int) -> list[str]:
    out: list[str] = []
    for item in value or ():
        text = _safe_text(item)
        if not text:
            continue
        if text not in allowed:
            raise ValueError(f"invalid closed code: {text!r}")
        if text not in out:
            out.append(text)
        if len(out) >= limit:
            break
    return out


def sanitize_oauth_hypothesis_plan(value: object) -> dict:
    """Project an R48.3 hypothesis onto its fixed bounded key set."""

    if not isinstance(value, dict):
        return {
            "rule_version": "",
            "hypothesis_type": TYPE_UNKNOWN,
            "hypothesis_state": STATE_UNKNOWN,
            "supporting_signals": [],
            "confidence": "UNKNOWN",
            "priority": "UNKNOWN",
            "rationale": "",
            "limitations": [],
            "research_only": True,
        }
    hypothesis_type = _safe_text(
        value.get("hypothesis_type")
    ).strip().upper()
    if hypothesis_type not in HYPOTHESIS_TYPES:
        hypothesis_type = TYPE_UNKNOWN
    hypothesis_state = _safe_text(
        value.get("hypothesis_state")
    ).strip().upper()
    if hypothesis_state not in HYPOTHESIS_STATES:
        hypothesis_state = STATE_UNKNOWN
    confidence = _safe_text(value.get("confidence")).strip().upper()
    if confidence not in CONFIDENCE_LEVELS:
        confidence = "UNKNOWN"
    priority = _safe_text(value.get("priority")).strip().upper()
    if priority not in CONFIDENCE_LEVELS:
        priority = "UNKNOWN"
    return {
        "rule_version": _safe_text(value.get("rule_version")),
        "hypothesis_type": hypothesis_type,
        "hypothesis_state": hypothesis_state,
        "supporting_signals": [
            signal
            for signal in (
                _safe_text(item)
                for item in value.get("supporting_signals") or ()
            )
            if signal in OAUTH_SIGNALS
        ][:MAX_SIGNALS],
        "confidence": confidence,
        "priority": priority,
        "rationale": _safe_text(value.get("rationale"), MAX_RATIONALE_LEN),
        "limitations": [
            code
            for code in (
                _safe_text(item) for item in value.get("limitations") or ()
            )
            if code in OAUTH_HYPOTHESIS_LIMITATIONS
        ][:MAX_LIMITATIONS],
        "research_only": True,
    }


# ---------------------------------------------------------------------------
# Model
# ---------------------------------------------------------------------------


class OAuthHypothesisPlan(BaseModel):
    """Deterministic research-only OAuth hypothesis (R48.3)."""

    model_config = ConfigDict(extra="forbid")

    rule_version: str = OAUTH_HYPOTHESIS_RULE_VERSION
    hypothesis_type: str
    hypothesis_state: str = STATE_UNKNOWN
    supporting_signals: list[str] = Field(default_factory=list)
    confidence: str = "UNKNOWN"
    priority: str = "UNKNOWN"
    rationale: str = ""
    limitations: list[str] = Field(default_factory=list)
    research_only: bool = True

    @field_validator("rule_version")
    @classmethod
    def _fixed_rule(cls, value: object) -> str:
        return OAUTH_HYPOTHESIS_RULE_VERSION

    @field_validator("hypothesis_type")
    @classmethod
    def _valid_type(cls, value: object) -> str:
        text = _safe_text(value).strip().upper()
        if text not in HYPOTHESIS_TYPES:
            raise ValueError(f"invalid hypothesis_type: {value!r}")
        return text

    @field_validator("hypothesis_state")
    @classmethod
    def _valid_state(cls, value: object) -> str:
        text = _safe_text(value).strip().upper()
        if text not in HYPOTHESIS_STATES:
            raise ValueError(f"invalid hypothesis_state: {value!r}")
        return text

    @field_validator("supporting_signals")
    @classmethod
    def _valid_signals(cls, value: list) -> list[str]:
        return _require_codes(value, OAUTH_SIGNALS, MAX_SIGNALS)

    @field_validator("confidence", "priority")
    @classmethod
    def _valid_confidence(cls, value: object) -> str:
        text = _safe_text(value).strip().upper()
        if text not in CONFIDENCE_LEVELS:
            raise ValueError(f"invalid confidence/priority: {value!r}")
        return text

    @field_validator("rationale")
    @classmethod
    def _bounded_rationale(cls, value: object) -> str:
        return _safe_text(value, MAX_RATIONALE_LEN)

    @field_validator("limitations")
    @classmethod
    def _valid_limitations(cls, value: list) -> list[str]:
        return _require_codes(
            value, OAUTH_HYPOTHESIS_LIMITATIONS, MAX_LIMITATIONS
        )

    @field_validator("research_only")
    @classmethod
    def _research_only(cls, value: object) -> bool:
        if not value:
            raise ValueError("oauth hypotheses are research-only")
        return True


def oauth_hypothesis_plan_projection(value: OAuthHypothesisPlan) -> dict:
    """Serialize an R48.3 hypothesis to a deterministic dict."""

    return value.model_dump(mode="json")


__all__ = [
    "OAUTH_HYPOTHESIS_RULE_VERSION",
    "RULE_VERSION",
    "TYPE_REDIRECT_URI_VALIDATION_GAP",
    "TYPE_STATE_VALIDATION_GAP",
    "TYPE_NONCE_VALIDATION_GAP",
    "TYPE_PKCE_ENFORCEMENT_GAP",
    "TYPE_PKCE_VERIFIER_VALIDATION_GAP",
    "TYPE_AUTHORIZATION_CODE_VALIDATION_GAP",
    "TYPE_AUTHORIZATION_CODE_REUSE_GAP",
    "TYPE_AUTHORIZATION_CODE_LIFETIME_RISK",
    "TYPE_CLIENT_AUTHENTICATION_GAP",
    "TYPE_CLIENT_CONFIGURATION_GAP",
    "TYPE_SCOPE_VALIDATION_GAP",
    "TYPE_RESOURCE_AUDIENCE_VALIDATION_GAP",
    "TYPE_ISSUER_VALIDATION_GAP",
    "TYPE_TOKEN_VALIDATION_GAP",
    "TYPE_REFRESH_TOKEN_ROTATION_GAP",
    "TYPE_REFRESH_TOKEN_REVOCATION_GAP",
    "TYPE_CONSENT_CONTROL_GAP",
    "TYPE_CSRF_PROTECTION_GAP",
    "TYPE_LOGIN_CSRF_GAP",
    "TYPE_REDIRECT_HANDLING_RISK",
    "TYPE_IMPLICIT_FLOW_RISK",
    "TYPE_TOKEN_EXPOSURE_RISK",
    "TYPE_AUTHORIZATION_FLOW_GAP",
    "TYPE_AUTHENTICATION_CONTROL_PRESENT",
    "TYPE_MISSING_OAUTH_CONTEXT",
    "TYPE_UNKNOWN",
    "HYPOTHESIS_TYPES",
    "VALIDATION_GAP_HYPOTHESIS_TYPES",
    "RISK_HYPOTHESIS_TYPES",
    "STATE_WEAKNESS_OBSERVED",
    "STATE_CONTROL_PRESENT_OBSERVED",
    "STATE_NEEDS_EVIDENCE",
    "STATE_NOT_OBSERVED",
    "STATE_UNKNOWN",
    "HYPOTHESIS_STATES",
    "SIGNAL_OAUTH2_OBSERVED",
    "SIGNAL_OAUTH2_1_OBSERVED",
    "SIGNAL_FLOW_AUTHORIZATION_CODE",
    "SIGNAL_FLOW_AUTHORIZATION_CODE_PKCE",
    "SIGNAL_FLOW_IMPLICIT",
    "SIGNAL_FLOW_CLIENT_CREDENTIALS",
    "SIGNAL_FLOW_DEVICE_AUTHORIZATION",
    "SIGNAL_FLOW_REFRESH_TOKEN",
    "SIGNAL_FLOW_HYBRID",
    "SIGNAL_CLIENT_TYPE_PUBLIC",
    "SIGNAL_CLIENT_TYPE_CONFIDENTIAL",
    "SIGNAL_AUTHORIZATION_SERVER_OBSERVED",
    "SIGNAL_RESOURCE_SERVER_OBSERVED",
    "SIGNAL_AUTHORIZATION_ENDPOINT_OBSERVED",
    "SIGNAL_TOKEN_ENDPOINT_OBSERVED",
    "SIGNAL_REDIRECT_URI_PARAM_OBSERVED",
    "SIGNAL_CLIENT_ID_OBSERVED",
    "SIGNAL_RESPONSE_TYPE_CODE",
    "SIGNAL_RESPONSE_TYPE_TOKEN",
    "SIGNAL_RESPONSE_TYPE_ID_TOKEN",
    "SIGNAL_GRANT_TYPE_AUTHORIZATION_CODE",
    "SIGNAL_GRANT_TYPE_REFRESH_TOKEN",
    "SIGNAL_GRANT_TYPE_CLIENT_CREDENTIALS",
    "SIGNAL_SCOPE_OBSERVED",
    "SIGNAL_STATE_PARAM_OBSERVED",
    "SIGNAL_NONCE_PARAM_OBSERVED",
    "SIGNAL_PKCE_CHALLENGE_OBSERVED",
    "SIGNAL_REDIRECT_URI_VALIDATION_ENFORCED",
    "SIGNAL_REDIRECT_URI_VALIDATION_ABSENT",
    "SIGNAL_REDIRECT_URI_VALIDATION_NOT_PROVIDED",
    "SIGNAL_EXACT_REDIRECT_MATCHING_ENFORCED",
    "SIGNAL_EXACT_REDIRECT_MATCHING_ABSENT",
    "SIGNAL_EXACT_REDIRECT_MATCHING_NOT_PROVIDED",
    "SIGNAL_STATE_VALIDATION_ENFORCED",
    "SIGNAL_STATE_VALIDATION_ABSENT",
    "SIGNAL_STATE_VALIDATION_NOT_PROVIDED",
    "SIGNAL_STATE_BINDING_ENFORCED",
    "SIGNAL_STATE_BINDING_ABSENT",
    "SIGNAL_STATE_BINDING_NOT_PROVIDED",
    "SIGNAL_NONCE_VALIDATION_ENFORCED",
    "SIGNAL_NONCE_VALIDATION_ABSENT",
    "SIGNAL_NONCE_VALIDATION_NOT_PROVIDED",
    "SIGNAL_PKCE_ENFORCEMENT_ENFORCED",
    "SIGNAL_PKCE_ENFORCEMENT_ABSENT",
    "SIGNAL_PKCE_ENFORCEMENT_NOT_PROVIDED",
    "SIGNAL_PKCE_VERIFIER_VALIDATION_ENFORCED",
    "SIGNAL_PKCE_VERIFIER_VALIDATION_ABSENT",
    "SIGNAL_PKCE_VERIFIER_VALIDATION_NOT_PROVIDED",
    "SIGNAL_AUTHORIZATION_CODE_BINDING_ENFORCED",
    "SIGNAL_AUTHORIZATION_CODE_BINDING_ABSENT",
    "SIGNAL_AUTHORIZATION_CODE_BINDING_NOT_PROVIDED",
    "SIGNAL_CODE_REUSE_CONTROL_ENFORCED",
    "SIGNAL_CODE_REUSE_CONTROL_ABSENT",
    "SIGNAL_CODE_REUSE_CONTROL_NOT_PROVIDED",
    "SIGNAL_CLIENT_AUTHENTICATION_ENFORCED",
    "SIGNAL_CLIENT_AUTHENTICATION_ABSENT",
    "SIGNAL_CLIENT_AUTHENTICATION_NOT_PROVIDED",
    "SIGNAL_SCOPE_VALIDATION_ENFORCED",
    "SIGNAL_SCOPE_VALIDATION_ABSENT",
    "SIGNAL_SCOPE_VALIDATION_NOT_PROVIDED",
    "SIGNAL_RESOURCE_AUDIENCE_VALIDATION_ENFORCED",
    "SIGNAL_RESOURCE_AUDIENCE_VALIDATION_ABSENT",
    "SIGNAL_RESOURCE_AUDIENCE_VALIDATION_NOT_PROVIDED",
    "SIGNAL_ISSUER_VALIDATION_ENFORCED",
    "SIGNAL_ISSUER_VALIDATION_ABSENT",
    "SIGNAL_ISSUER_VALIDATION_NOT_PROVIDED",
    "SIGNAL_TOKEN_VALIDATION_ENFORCED",
    "SIGNAL_TOKEN_VALIDATION_ABSENT",
    "SIGNAL_TOKEN_VALIDATION_NOT_PROVIDED",
    "SIGNAL_REFRESH_TOKEN_ROTATION_ENFORCED",
    "SIGNAL_REFRESH_TOKEN_ROTATION_ABSENT",
    "SIGNAL_REFRESH_TOKEN_ROTATION_NOT_PROVIDED",
    "SIGNAL_REFRESH_TOKEN_REVOCATION_ENFORCED",
    "SIGNAL_REFRESH_TOKEN_REVOCATION_ABSENT",
    "SIGNAL_REFRESH_TOKEN_REVOCATION_NOT_PROVIDED",
    "SIGNAL_CONSENT_CONTROL_ENFORCED",
    "SIGNAL_CONSENT_CONTROL_ABSENT",
    "SIGNAL_CONSENT_CONTROL_NOT_PROVIDED",
    "SIGNAL_CSRF_PROTECTION_ENFORCED",
    "SIGNAL_CSRF_PROTECTION_ABSENT",
    "SIGNAL_CSRF_PROTECTION_NOT_PROVIDED",
    "SIGNAL_LOGIN_CSRF_PROTECTION_ENFORCED",
    "SIGNAL_LOGIN_CSRF_PROTECTION_ABSENT",
    "SIGNAL_LOGIN_CSRF_PROTECTION_NOT_PROVIDED",
    "SIGNAL_REDIRECT_HANDLING_ENFORCED",
    "SIGNAL_REDIRECT_HANDLING_ABSENT",
    "SIGNAL_REDIRECT_HANDLING_NOT_PROVIDED",
    "SIGNAL_REDIRECT_REGISTRATION_EXACT",
    "SIGNAL_REDIRECT_REGISTRATION_WILDCARD",
    "SIGNAL_CODE_LIFETIME_SHORT",
    "SIGNAL_CODE_LIFETIME_LONG",
    "SIGNAL_CODE_LIFETIME_UNBOUNDED",
    "SIGNAL_TOKEN_AUTH_CLIENT_SECRET_BASIC",
    "SIGNAL_TOKEN_AUTH_CLIENT_SECRET_POST",
    "SIGNAL_TOKEN_AUTH_PRIVATE_KEY_JWT",
    "SIGNAL_TOKEN_AUTH_TLS_CLIENT_AUTH",
    "SIGNAL_TOKEN_AUTH_NONE_OBSERVED",
    "SIGNAL_CLIENT_SECRET_REQUIRED",
    "SIGNAL_CLIENT_SECRET_NOT_REQUIRED",
    "SIGNAL_REFRESH_TOKEN_OBSERVED",
    "SIGNAL_TOKEN_EXPOSURE_URL",
    "SIGNAL_TOKEN_EXPOSURE_BROWSER_STORAGE",
    "SIGNAL_TOKEN_EXPOSURE_RESPONSE_BODY",
    "SIGNAL_TOKEN_EXPOSURE_LOG",
    "SIGNAL_TOKEN_EXPOSURE_REFERRER",
    "SIGNAL_TOKEN_EXPOSURE_CLIENT_STORAGE",
    "SIGNAL_AUTHORIZATION_BOUNDARY_SERVER_SIDE",
    "SIGNAL_AUTHORIZATION_BOUNDARY_CLIENT_SIDE",
    "SIGNAL_SESSION_SERVER_SIDE",
    "SIGNAL_SESSION_CLIENT_SIDE",
    "SIGNAL_SESSION_STATELESS_TOKEN",
    "SIGNAL_MISSING_OAUTH_CONTEXT",
    "SIGNAL_CONTEXT_UNKNOWN",
    "OAUTH_SIGNALS",
    "LIMITATION_NO_EXPLOIT_CLAIM",
    "LIMITATION_NO_VULNERABILITY_CONFIRMATION",
    "LIMITATION_NO_OAUTH_BYPASS_CLAIM",
    "LIMITATION_NO_REDIRECT_URI_EXPLOIT_CLAIM",
    "LIMITATION_NO_TOKEN_EXCHANGE_CLAIM",
    "LIMITATION_NO_CSRF_EXPLOIT_CLAIM",
    "LIMITATION_HYPOTHESIS_ONLY",
    "LIMITATION_EVIDENCE_REQUIRED",
    "LIMITATION_INSUFFICIENT_CONTEXT",
    "OAUTH_HYPOTHESIS_LIMITATIONS",
    "MAX_SIGNALS",
    "MAX_LIMITATIONS",
    "MAX_VALUE_LEN",
    "MAX_RATIONALE_LEN",
    "sanitize_oauth_hypothesis_plan",
    "OAuthHypothesisPlan",
    "oauth_hypothesis_plan_projection",
]
